package com.amcl.launcher;

import java.io.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;

/**
 * Forge 特有的预处理逻辑。
 * 在 Java 层、MC main() 之前执行，比 C 层/ArkTS 层更可靠。
 *
 * 核心职责：在正确路径创建/更新 config/fml.toml，禁用 EarlyDisplay。
 * 因为在 Java 层执行，System.getProperty("user.dir") 已经是 gameDir，
 * 路径一定正确，不再有 user.home 困境。
 */
public class ForgeHelper {

    private static final String FML_CLIENT_SECTION = "[fmlClient]";

    private static final String[][] EARLY_DISPLAY_KEYS = {
        {"earlyWindowControl", "false"},
        {"earlyWindowShowCPU", "false"},
        {"earlyWindowSquir", "false"},
        {"earlyWindowLogHelpMessage", "false"},
    };

    /**
     * 禁用 Forge EarlyDisplay。
     * 如果 config.isForge 为 false，不做任何操作。
     */
    public static void disableEarlyDisplay(LaunchConfig config) {
        if (config == null || !config.isForge) return;

        // 写入 gameDir/config/ 和 mcDir/config/（如果不同）
        writeToPath(config.gameDir);
        if (config.mcDir != null && !config.mcDir.equals(config.gameDir)) {
            writeToPath(config.mcDir);
        }
    }

    /**
     * 禁用旧版 Forge（1.12.2 及以下）的 splash screen。
     * 参考 Amethyst-iOS PojavLauncher.java:
     *   forgeSplashFile = new File(DIR_GAME_NEW, "config/splash.properties");
     *   Tools.write(forgeSplashFile, "enabled=false");
     */
    public static void disableForgeSplash(LaunchConfig config) {
        if (config == null || !config.isForge) return;

        String[] dirs = { config.gameDir, config.mcDir };
        for (String dir : dirs) {
            if (dir == null || dir.isEmpty()) continue;
            Path splashPath = Paths.get(dir, "config", "splash.properties");
            try {
                Files.createDirectories(splashPath.getParent());
                if (Files.exists(splashPath)) {
                    String content = new String(Files.readAllBytes(splashPath), StandardCharsets.UTF_8);
                    String updated = content.replace("enabled=true", "enabled=false");
                    if (!updated.equals(content)) {
                        Files.write(splashPath, updated.getBytes(StandardCharsets.UTF_8));
                        System.out.println("[ForgeHelper] Patched splash.properties: " + splashPath);
                    }
                } else {
                    Files.write(splashPath, "enabled=false\n".getBytes(StandardCharsets.UTF_8));
                    System.out.println("[ForgeHelper] Created splash.properties: " + splashPath);
                }
            } catch (IOException e) {
                System.err.println("[ForgeHelper] Failed to patch splash.properties: " + e.getMessage());
            }
        }
    }

    private static void writeToPath(String baseDir) {
        if (baseDir == null || baseDir.isEmpty()) return;
        Path configDir = Paths.get(baseDir, "config");
        Path tomlPath = configDir.resolve("fml.toml");

        try {
            Files.createDirectories(configDir);

            String content;
            if (Files.exists(tomlPath)) {
                content = new String(Files.readAllBytes(tomlPath), StandardCharsets.UTF_8);
            } else {
                content = "";
            }

            String updated = patchContent(content);

            if (!updated.equals(content)) {
                Files.write(tomlPath, updated.getBytes(StandardCharsets.UTF_8));
                System.out.println("[ForgeHelper] Patched: " + tomlPath);
            }
        } catch (IOException e) {
            System.err.println("[ForgeHelper] Failed to write " + tomlPath + ": " + e.getMessage());
        }
    }

    /**
     * 在 fml.toml 内容中设置 EarlyDisplay 相关的 key（扁平顶层格式）。
     *
     * ⚠️ 2026-06-06 修复：Forge 1.17+ 的 fml.toml 是【扁平】的——earlyWindowControl 等
     * 是【顶层 key】，不存在 [fmlClient] 段。历史代码把这些 key 写进 [fmlClient] 段，
     * 导致 Forge 在顶层找不到 earlyWindowControl → 用默认值 true → 加载 EarlyDisplay →
     * 在 OHOS 上卡在 Forge 加载界面（1.21.5）/ 首次启动失败、后续偶然收敛（1.21.6）。
     * 现在改为：删除历史误加的 [fmlClient] 段头（把段内 key 还原为顶层），并以顶层方式
     * upsert 每个 key。
     */
    static String patchContent(String content) {
        String result = content;

        // 确保文件非空
        if (result.isEmpty()) {
            result = "# Auto-generated by AMCL\n";
        }

        // 删除历史上误加的 [fmlClient] 段头（Forge 扁平 schema 下它是非法的，会让 Forge
        // 判定 "not correct" 并把我们段内的 key 一并丢弃 → 重置为默认 true）。
        result = result.replace(FML_CLIENT_SECTION + "\n", "").replace(FML_CLIENT_SECTION, "");

        // 以顶层（扁平）方式设置每个 key
        for (String[] kv : EARLY_DISPLAY_KEYS) {
            result = upsertKey(result, kv[0], kv[1]);
        }

        return result;
    }

    /**
     * 顶层（扁平）设置 key = value。
     * key 已存在（任意位置的顶层行）→ 原地替换；不存在 → 追加到末尾（扁平文件末尾即顶层）。
     */
    private static String upsertKey(String content, String key, String value) {
        String line = key + " = " + value;

        // 匹配 "key = ..." 或 "key=..."（行首，允许前导空白）
        String regex = "(?m)^\\s*" + key + "\\s*=.*$";
        if (content.matches("(?s).*" + regex + ".*")) {
            return content.replaceFirst(regex, line);
        }

        // 不存在 → 追加到末尾（扁平 fml.toml 无 section，末尾即顶层 key）
        if (!content.endsWith("\n")) content += "\n";
        return content + line + "\n";
    }
}
