/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiWindowClass */

#ifndef _Included_imgui_ImGuiWindowClass
#define _Included_imgui_ImGuiWindowClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiWindowClass_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    geClassId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiWindowClass_geClassId
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    setClassId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_setClassId
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    getParentViewportId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiWindowClass_getParentViewportId
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    setParentViewportId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_setParentViewportId
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    getViewportFlagsOverrideSet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiWindowClass_getViewportFlagsOverrideSet
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    setViewportFlagsOverrideSet
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_setViewportFlagsOverrideSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    getViewportFlagsOverrideClear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiWindowClass_getViewportFlagsOverrideClear
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    setViewportFlagsOverrideClear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_setViewportFlagsOverrideClear
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    getTabItemFlagsOverrideSet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiWindowClass_getTabItemFlagsOverrideSet
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    setTabItemFlagsOverrideSet
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_setTabItemFlagsOverrideSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    getDockNodeFlagsOverrideSet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiWindowClass_getDockNodeFlagsOverrideSet
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    setDockNodeFlagsOverrideSet
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_setDockNodeFlagsOverrideSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    getDockingAlwaysTabBar
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiWindowClass_getDockingAlwaysTabBar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    setDockingAlwaysTabBar
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_setDockingAlwaysTabBar
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    getDockingAllowUnclassed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiWindowClass_getDockingAllowUnclassed
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiWindowClass
 * Method:    setDockingAllowUnclassed
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiWindowClass_setDockingAllowUnclassed
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
