/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_internal_ImGui */

#ifndef _Included_imgui_internal_ImGui
#define _Included_imgui_internal_ImGui
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_internal_ImGui
 * Method:    calcItemSize
 * Signature: (FFFFLimgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_calcItemSize
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jobject);

/*
 * Class:     imgui_internal_ImGui
 * Method:    calcItemSizeX
 * Signature: (FFFF)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGui_calcItemSizeX
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    calcItemSizeY
 * Signature: (FFFF)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGui_calcItemSizeY
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    pushItemFlag
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_pushItemFlag
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     imgui_internal_ImGui
 * Method:    popItemFlag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_popItemFlag
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    dockBuilderDockWindow
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_dockBuilderDockWindow
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderGetNode
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGui_nDockBuilderGetNode
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderGetCentralNode
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGui_nDockBuilderGetCentralNode
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    dockBuilderAddNode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_dockBuilderAddNode__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    dockBuilderAddNode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_dockBuilderAddNode__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    dockBuilderAddNode
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_dockBuilderAddNode__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    dockBuilderRemoveNode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_dockBuilderRemoveNode
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    dockBuilderRemoveNodeDockedWindows
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_dockBuilderRemoveNodeDockedWindows__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    dockBuilderRemoveNodeDockedWindows
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_dockBuilderRemoveNodeDockedWindows__IZ
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     imgui_internal_ImGui
 * Method:    dockBuilderRemoveNodeChildNodes
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_dockBuilderRemoveNodeChildNodes
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    dockBuilderSetNodePos
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_dockBuilderSetNodePos
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    dockBuilderSetNodeSize
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_dockBuilderSetNodeSize
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderSplitNode
 * Signature: (IIF[I[I)I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nDockBuilderSplitNode__IIF_3I_3I
  (JNIEnv *, jclass, jint, jint, jfloat, jintArray, jintArray);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderSplitNode
 * Signature: (IIF)I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nDockBuilderSplitNode__IIF
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderSplitNode
 * Signature: (IIF[I)I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nDockBuilderSplitNode__IIF_3I
  (JNIEnv *, jclass, jint, jint, jfloat, jintArray);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nDockBuilderSplitNode
 * Signature: (IIFI[I)I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGui_nDockBuilderSplitNode__IIFI_3I
  (JNIEnv *, jclass, jint, jint, jfloat, jint, jintArray);

/*
 * Class:     imgui_internal_ImGui
 * Method:    dockBuilderCopyWindowSettings
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_dockBuilderCopyWindowSettings
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     imgui_internal_ImGui
 * Method:    dockBuilderFinish
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_dockBuilderFinish
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nSplitterBehaviour
 * Signature: (FFFFII[F[FFFFFI)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGui_nSplitterBehaviour
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jint, jint, jfloatArray, jfloatArray, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetCurrentWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGui_nGetCurrentWindow
  (JNIEnv *, jclass);

/*
 * Class:     imgui_internal_ImGui
 * Method:    nGetWindowScrollbarRect
 * Signature: (JILimgui/ImVec2;Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGui_nGetWindowScrollbarRect
  (JNIEnv *, jclass, jlong, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
