/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_texteditor_TextEditor */

#ifndef _Included_imgui_extension_texteditor_TextEditor
#define _Included_imgui_extension_texteditor_TextEditor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditor_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetLanguageDefinition
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetLanguageDefinition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getPalette
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_imgui_extension_texteditor_TextEditor_getPalette
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetPalette
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetPalette
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetErrorMarkers
 * Signature: ([II[Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetErrorMarkers
  (JNIEnv *, jobject, jintArray, jint, jobjectArray, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetBreakpoints
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetBreakpoints
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    render
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_render
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    setText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_setText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditor_getText
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    nSetTextLines
 * Signature: ([Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_nSetTextLines
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getTextLines
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_imgui_extension_texteditor_TextEditor_getTextLines
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getSelectedText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditor_getSelectedText
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getCurrentLineText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_texteditor_TextEditor_getCurrentLineText
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getTotalLines
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_texteditor_TextEditor_getTotalLines
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    isOverwrite
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_isOverwrite
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    setReadOnly
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_setReadOnly
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    isReadOnly
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_isReadOnly
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    isTextChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_isTextChanged
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    isCursorPositionChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_isCursorPositionChanged
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    isColorizerEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_isColorizerEnabled
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    setColorizerEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_setColorizerEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getCursorPositionLine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_texteditor_TextEditor_getCursorPositionLine
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getCursorPositionColumn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_texteditor_TextEditor_getCursorPositionColumn
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    setCursorPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_setCursorPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    setHandleMouseInputs
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_setHandleMouseInputs
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    isHandleMouseInputsEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_isHandleMouseInputsEnabled
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    setHandleKeyboardInputs
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_setHandleKeyboardInputs
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    isHandleKeyboardInputsEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_isHandleKeyboardInputsEnabled
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    setImGuiChildIgnored
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_setImGuiChildIgnored
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    isImGuiChildIgnored
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_isImGuiChildIgnored
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    setShowWhitespaces
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_setShowWhitespaces
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    isShowingWhitespaces
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_isShowingWhitespaces
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    setTabSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_setTabSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getTabSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_texteditor_TextEditor_getTabSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    insertText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_insertText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    moveUp
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_moveUp
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    moveDown
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_moveDown
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    moveLeft
 * Signature: (IZZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_moveLeft
  (JNIEnv *, jobject, jint, jboolean, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    moveRight
 * Signature: (IZZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_moveRight
  (JNIEnv *, jobject, jint, jboolean, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    moveTop
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_moveTop
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    moveBottom
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_moveBottom
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    moveHome
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_moveHome
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    moveEnd
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_moveEnd
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    setSelectionStart
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_setSelectionStart
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    setSelectionEnd
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_setSelectionEnd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    setSelection
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_setSelection
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    selectWordUnderCursor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_selectWordUnderCursor
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    selectAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_selectAll
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    hasSelection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_hasSelection
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    copy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_copy
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    cut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_cut
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    paste
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_paste
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_delete
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    canUndo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_canUndo
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    canRedo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_texteditor_TextEditor_canRedo
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    undo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_undo
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    redo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditor_redo
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getDarkPalette
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_imgui_extension_texteditor_TextEditor_getDarkPalette
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getLightPalette
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_imgui_extension_texteditor_TextEditor_getLightPalette
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditor
 * Method:    getRetroBluePalette
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_imgui_extension_texteditor_TextEditor_getRetroBluePalette
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
