/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImFont */

#ifndef _Included_imgui_ImFont
#define _Included_imgui_ImFont
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImFont
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFont_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    getFallbackAdvanceX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFont_getFallbackAdvanceX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    setFallbackAdvanceX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_setFallbackAdvanceX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    getFontSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFont_getFontSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    nGetFallbackGlyphPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFont_nGetFallbackGlyphPtr
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    getConfigDataCount
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_imgui_ImFont_getConfigDataCount
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    getFallbackChar
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_imgui_ImFont_getFallbackChar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    getEllipsisChar
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_imgui_ImFont_getEllipsisChar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    setEllipsisChar
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_setEllipsisChar
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFont
 * Method:    getDotChar
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_imgui_ImFont_getDotChar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    setDotChar
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_setDotChar
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFont
 * Method:    getDirtyLookupTables
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImFont_getDirtyLookupTables
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    setDirtyLookupTables
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_setDirtyLookupTables
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImFont
 * Method:    getScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFont_getScale
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    setScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_setScale
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    getAscent
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFont_getAscent
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    setAscent
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_setAscent
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    getDescent
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFont_getDescent
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    setDescent
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_setDescent
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    getMetricsTotalSurface
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFont_getMetricsTotalSurface
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    setMetricsTotalSurface
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_setMetricsTotalSurface
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFont
 * Method:    nFindGlyph
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFont_nFindGlyph
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFont
 * Method:    nFindGlyphNoFallback
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFont_nFindGlyphNoFallback
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFont
 * Method:    getCharAdvance
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFont_getCharAdvance
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFont
 * Method:    isLoaded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImFont_isLoaded
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    getDebugName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_ImFont_getDebugName
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFont
 * Method:    calcTextSizeA
 * Signature: (Limgui/ImVec2;FFFLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_calcTextSizeA
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jfloat, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    calcTextSizeAX
 * Signature: (FFFLjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFont_calcTextSizeAX
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    calcTextSizeAY
 * Signature: (FFFLjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFont_calcTextSizeAY
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jstring);

/*
 * Class:     imgui_ImFont
 * Method:    calcWordWrapPositionA
 * Signature: (FLjava/lang/String;Ljava/lang/String;F)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_ImFont_calcWordWrapPositionA
  (JNIEnv *, jobject, jfloat, jstring, jstring, jfloat);

/*
 * Class:     imgui_ImFont
 * Method:    nRenderChar
 * Signature: (JFFFII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_nRenderChar
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_ImFont
 * Method:    nRenderText
 * Signature: (JFFFIFFFFLjava/lang/String;Ljava/lang/String;FZ)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFont_nRenderText
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jint, jfloat, jfloat, jfloat, jfloat, jstring, jstring, jfloat, jboolean);

#ifdef __cplusplus
}
#endif
#endif
