/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_implot_ImPlotRange */

#ifndef _Included_imgui_extension_implot_ImPlotRange
#define _Included_imgui_extension_implot_ImPlotRange
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_implot_ImPlotRange
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlotRange_create__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotRange
 * Method:    create
 * Signature: (DD)J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlotRange_create__DD
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     imgui_extension_implot_ImPlotRange
 * Method:    contains
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlotRange_contains
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     imgui_extension_implot_ImPlotRange
 * Method:    size
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_imgui_extension_implot_ImPlotRange_size
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotRange
 * Method:    getMin
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_imgui_extension_implot_ImPlotRange_getMin
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotRange
 * Method:    getMax
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_imgui_extension_implot_ImPlotRange_getMax
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotRange
 * Method:    setMin
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotRange_setMin
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     imgui_extension_implot_ImPlotRange
 * Method:    nSetMax
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotRange_nSetMax
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
