/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImFontAtlas */

#ifndef _Included_imgui_ImFontAtlas
#define _Included_imgui_ImFontAtlas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImFontAtlas
 * Method:    nInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_nInit
  (JNIEnv *, jclass);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFont
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFont
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontDefault
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontDefault__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontDefault
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontDefault__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromFileTTF
 * Signature: (Ljava/lang/String;F)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromFileTTF__Ljava_lang_String_2F
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromFileTTF
 * Signature: (Ljava/lang/String;FJ)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromFileTTF__Ljava_lang_String_2FJ
  (JNIEnv *, jobject, jstring, jfloat, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromFileTTF
 * Signature: (Ljava/lang/String;F[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromFileTTF__Ljava_lang_String_2F_3S
  (JNIEnv *, jobject, jstring, jfloat, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromFileTTF
 * Signature: (Ljava/lang/String;FJ[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromFileTTF__Ljava_lang_String_2FJ_3S
  (JNIEnv *, jobject, jstring, jfloat, jlong, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryTTF
 * Signature: ([BIF)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryTTF___3BIF
  (JNIEnv *, jobject, jbyteArray, jint, jfloat);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryTTF
 * Signature: ([BIFJ)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryTTF___3BIFJ
  (JNIEnv *, jobject, jbyteArray, jint, jfloat, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryTTF
 * Signature: ([BIF[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryTTF___3BIF_3S
  (JNIEnv *, jobject, jbyteArray, jint, jfloat, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryTTF
 * Signature: ([BIFJ[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryTTF___3BIFJ_3S
  (JNIEnv *, jobject, jbyteArray, jint, jfloat, jlong, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedTTF
 * Signature: ([BIF)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedTTF___3BIF
  (JNIEnv *, jobject, jbyteArray, jint, jfloat);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedTTF
 * Signature: ([BIFJ)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedTTF___3BIFJ
  (JNIEnv *, jobject, jbyteArray, jint, jfloat, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedTTF
 * Signature: ([BIF[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedTTF___3BIF_3S
  (JNIEnv *, jobject, jbyteArray, jint, jfloat, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedTTF
 * Signature: ([BIFJ[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedTTF___3BIFJ_3S
  (JNIEnv *, jobject, jbyteArray, jint, jfloat, jlong, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedBase85TTF
 * Signature: (Ljava/lang/String;F)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedBase85TTF__Ljava_lang_String_2F
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedBase85TTF
 * Signature: (Ljava/lang/String;FJ)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedBase85TTF__Ljava_lang_String_2FJ
  (JNIEnv *, jobject, jstring, jfloat, jlong);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedBase85TTF
 * Signature: (Ljava/lang/String;F[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedBase85TTF__Ljava_lang_String_2F_3S
  (JNIEnv *, jobject, jstring, jfloat, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddFontFromMemoryCompressedBase85TTF
 * Signature: (Ljava/lang/String;FJ[S)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontAtlas_nAddFontFromMemoryCompressedBase85TTF__Ljava_lang_String_2FJ_3S
  (JNIEnv *, jobject, jstring, jfloat, jlong, jshortArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    clearInputData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_clearInputData
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    clearTexData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_clearTexData
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    clearFonts
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_clearFonts
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_clear
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    build
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImFontAtlas_build
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getTexDataAsAlpha8
 * Signature: ([I[I[I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_getTexDataAsAlpha8
  (JNIEnv *, jobject, jintArray, jintArray, jintArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nGetTexDataAsRGBA32
 * Signature: ([I[I[I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_nGetTexDataAsRGBA32
  (JNIEnv *, jobject, jintArray, jintArray, jintArray);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    isBuilt
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImFontAtlas_isBuilt
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    setTexID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_setTexID
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesDefault
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesDefault
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesKorean
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesKorean
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesJapanese
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesJapanese
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesChineseFull
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesChineseFull
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesChineseSimplifiedCommon
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesChineseSimplifiedCommon
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesCyrillic
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesCyrillic
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesThai
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesThai
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getGlyphRangesVietnamese
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_imgui_ImFontAtlas_getGlyphRangesVietnamese
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    addCustomRectRegular
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontAtlas_addCustomRectRegular
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddCustomRectFontGlyph
 * Signature: (JSIIF)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontAtlas_nAddCustomRectFontGlyph__JSIIF
  (JNIEnv *, jobject, jlong, jshort, jint, jint, jfloat);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    nAddCustomRectFontGlyph
 * Signature: (JSIIFFF)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontAtlas_nAddCustomRectFontGlyph__JSIIFFF
  (JNIEnv *, jobject, jlong, jshort, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getLocked
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImFontAtlas_getLocked
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    setLocked
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_setLocked
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontAtlas_getFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    setFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_setFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getTexID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontAtlas_getTexID
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getTexDesiredWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontAtlas_getTexDesiredWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    setTexDesiredWidth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_setTexDesiredWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    getTexGlyphPadding
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontAtlas_getTexGlyphPadding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontAtlas
 * Method:    setTexGlyphPadding
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontAtlas_setTexGlyphPadding
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
