/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_imguifiledialog_ImGuiFileDialog */

#ifndef _Included_imgui_extension_imguifiledialog_ImGuiFileDialog
#define _Included_imgui_extension_imguifiledialog_ImGuiFileDialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    openDialog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IJI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_openDialog
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jint, jlong, jint);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    openModal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IJI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_openModal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IJI
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jint, jlong, jint);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    openModal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IJI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_openModal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IJI
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint, jlong, jint);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    openModal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Limgui/extension/imguifiledialog/callback/ImGuiFileDialogPaneFun;FIJI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_openModal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Limgui_extension_imguifiledialog_callback_ImGuiFileDialogPaneFun_2FIJI
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jobject, jfloat, jint, jlong, jint);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    openModal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Limgui/extension/imguifiledialog/callback/ImGuiFileDialogPaneFun;FIJI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_openModal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Limgui_extension_imguifiledialog_callback_ImGuiFileDialogPaneFun_2FIJI
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jobject, jfloat, jint, jlong, jint);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    display
 * Signature: (Ljava/lang/String;IFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_display
  (JNIEnv *, jclass, jstring, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_close
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    wasOpenedThisFrame
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_wasOpenedThisFrame__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    wasOpenedThisFrame
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_wasOpenedThisFrame__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    isOpened
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_isOpened__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    isOpened
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_isOpened__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    getOpenedKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_getOpenedKey
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    isOk
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_isOk
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    getSelection
 * Signature: ()Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_getSelection
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    getFilePathName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_getFilePathName
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    getCurrentFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_getCurrentFileName
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    getCurrentPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_getCurrentPath
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    getCurrentFilter
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_getCurrentFilter
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imguifiledialog_ImGuiFileDialog
 * Method:    getUserDatas
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_imguifiledialog_ImGuiFileDialog_getUserDatas
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
