/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_nodeditor_NodeEditorConfig */

#ifndef _Included_imgui_extension_nodeditor_NodeEditorConfig
#define _Included_imgui_extension_nodeditor_NodeEditorConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    getSettingsFile
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_getSettingsFile
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorConfig
 * Method:    setSettingsFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorConfig_setSettingsFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
