/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_texteditor_TextEditorLanguageDefinition */

#ifndef _Included_imgui_extension_texteditor_TextEditorLanguageDefinition
#define _Included_imgui_extension_texteditor_TextEditorLanguageDefinition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    setName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_setName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    nSetKeywords
 * Signature: ([Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_nSetKeywords
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    nSetIdentifiers
 * Signature: ([Ljava/lang/String;I[Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_nSetIdentifiers
  (JNIEnv *, jobject, jobjectArray, jint, jobjectArray, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    nSetPreprocIdentifiers
 * Signature: ([Ljava/lang/String;I[Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_nSetPreprocIdentifiers
  (JNIEnv *, jobject, jobjectArray, jint, jobjectArray, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    setCommentStart
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_setCommentStart
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    setCommentEnd
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_setCommentEnd
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    setSingleLineComment
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_setSingleLineComment
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    setPreprocChar
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_setPreprocChar
  (JNIEnv *, jobject, jchar);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    setAutoIdentation
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_setAutoIdentation
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    nSetTokenRegexStrings
 * Signature: ([Ljava/lang/String;I[II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_nSetTokenRegexStrings
  (JNIEnv *, jobject, jobjectArray, jint, jintArray, jint);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    setCaseSensitive
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_setCaseSensitive
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    nCPlusPlus
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_nCPlusPlus
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    nHLSL
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_nHLSL
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    nGLSL
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_nGLSL
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    nC
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_nC
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    nSQL
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_nSQL
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    nAngelScript
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_nAngelScript
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_texteditor_TextEditorLanguageDefinition
 * Method:    nLua
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_texteditor_TextEditorLanguageDefinition_nLua
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
