/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_implot_ImPlotStyle */

#ifndef _Included_imgui_extension_implot_ImPlotStyle
#define _Included_imgui_extension_implot_ImPlotStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    getLineWeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_getLineWeight
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    setLineWeight
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_setLineWeight
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    getMarker
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotStyle_getMarker
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    setMarker
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_setMarker
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    getMarkerSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_getMarkerSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    setMarkerSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_setMarkerSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    getMarkerWeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_getMarkerWeight
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    setMarkerWeight
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_setMarkerWeight
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    getFillAlpha
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_getFillAlpha
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    setFillAlpha
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_setFillAlpha
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    getErrorBarSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_getErrorBarSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    setErrorBarSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_setErrorBarSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    getErrorBarWeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_getErrorBarWeight
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    setErrorBarWeight
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_setErrorBarWeight
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    getDigitalBitHeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_getDigitalBitHeight
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    setDigitalBitHeight
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_setDigitalBitHeight
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    getDigitalBitGap
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_getDigitalBitGap
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    setDigitalBitGap
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_setDigitalBitGap
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    getPlotBorderSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_getPlotBorderSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    setPlotBorderSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_setPlotBorderSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    getMinorAlpha
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlotStyle_getMinorAlpha
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    setMinorAlpha
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_setMinorAlpha
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMajorTickLen
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMajorTickLen
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetMajorTickLen
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetMajorTickLen
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMinorTickLen
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMinorTickLen
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetMinorTickLen
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetMinorTickLen
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMajorTickSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMajorTickSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetMajorTickSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetMajorTickSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMinorTickSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMinorTickSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetMinorTickSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetMinorTickSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMajorGridSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMajorGridSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetMajorGridSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetMajorGridSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMinorGridSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMinorGridSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetMinorGridSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetMinorGridSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetPlotPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetPlotPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetPlotPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetPlotPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetLabelPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetLabelPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetLabelPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetLabelPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetLegendPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetLegendPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetLegendPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetLegendPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetLegendInnerPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetLegendInnerPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetLegendInnerPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetLegendInnerPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetLegendSpacing
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetLegendSpacing
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetLegendSpacing
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetLegendSpacing
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetMousePosPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetMousePosPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetMousePosPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetMousePosPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetAnnotationPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetAnnotationPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetAnnotationPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetAnnotationPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetFitPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetFitPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetFitPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetFitPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetPlotDefaultSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetPlotDefaultSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetPlotDefaultSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetPlotDefaultSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetPlotMinSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetPlotMinSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetPlotMinSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetPlotMinSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nGetColors
 * Signature: ([F[F[F[FI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nGetColors
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jint);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    nSetColors
 * Signature: ([F[F[F[FI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_nSetColors
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jint);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    getColormap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlotStyle_getColormap
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    setColormap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_setColormap
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    isAntiAliasedLines
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlotStyle_isAntiAliasedLines
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    setAntiAliasedLines
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_setAntiAliasedLines
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    isUseLocalTime
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlotStyle_isUseLocalTime
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    setUseLocalTime
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_setUseLocalTime
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    isUseISO8601
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlotStyle_isUseISO8601
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    setUseISO8601
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_setUseISO8601
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    isUse24HourClock
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlotStyle_isUse24HourClock
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotStyle
 * Method:    setUse24HourClock
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotStyle_setUse24HourClock
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
