/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImDrawList */

#ifndef _Included_imgui_ImDrawList
#define _Included_imgui_ImDrawList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImDrawList
 * Method:    getImDrawListFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawList_getImDrawListFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    setImDrawListFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_setImDrawListFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    pushClipRect
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pushClipRect__FFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    pushClipRect
 * Signature: (FFFFZ)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pushClipRect__FFFFZ
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jboolean);

/*
 * Class:     imgui_ImDrawList
 * Method:    pushClipRectFullScreen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pushClipRectFullScreen
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    popClipRect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_popClipRect
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    pushTextureId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pushTextureId
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    popTextureId
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_popTextureId
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    getClipRectMin
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_getClipRectMin
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    getClipRectMinX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawList_getClipRectMinX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    getClipRectMinY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawList_getClipRectMinY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    getClipRectMax
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_getClipRectMax
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    getClipRectMaxX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawList_getClipRectMaxX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    getClipRectMaxY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawList_getClipRectMaxY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    addLine
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addLine__FFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addLine
 * Signature: (FFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addLine__FFFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addRect
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addRect__FFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addRect
 * Signature: (FFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addRect__FFFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addRect
 * Signature: (FFFFIFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addRect__FFFFIFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addRect
 * Signature: (FFFFIFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addRect__FFFFIFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addRectFilled
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addRectFilled__FFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addRectFilled
 * Signature: (FFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addRectFilled__FFFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addRectFilled
 * Signature: (FFFFIFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addRectFilled__FFFFIFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addRectFilledMultiColor
 * Signature: (FFFFJJJJ)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addRectFilledMultiColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jlong, jlong, jlong, jlong);

/*
 * Class:     imgui_ImDrawList
 * Method:    addQuad
 * Signature: (FFFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addQuad__FFFFFFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addQuad
 * Signature: (FFFFFFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addQuad__FFFFFFFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addQuadFilled
 * Signature: (FFFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addQuadFilled
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addTriangle
 * Signature: (FFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addTriangle__FFFFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addTriangle
 * Signature: (FFFFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addTriangle__FFFFFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addTriangleFilled
 * Signature: (FFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addTriangleFilled
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addCircle
 * Signature: (FFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addCircle__FFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addCircle
 * Signature: (FFFII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addCircle__FFFII
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addCircle
 * Signature: (FFFIIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addCircle__FFFIIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addCircleFilled
 * Signature: (FFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addCircleFilled__FFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addCircleFilled
 * Signature: (FFFII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addCircleFilled__FFFII
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addNgon
 * Signature: (FFFII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addNgon__FFFII
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addNgon
 * Signature: (FFFIIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addNgon__FFFIIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addNgonFilled
 * Signature: (FFFII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addNgonFilled
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addText
 * Signature: (FFILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addText
  (JNIEnv *, jobject, jfloat, jfloat, jint, jstring);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddText
 * Signature: (JFFFILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddText__JFFFILjava_lang_String_2
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jint, jstring);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddText
 * Signature: (JFFFILjava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddText__JFFFILjava_lang_String_2F
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jint, jstring, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    nAddText
 * Signature: (JFFFILjava/lang/String;FFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_nAddText__JFFFILjava_lang_String_2FFFFF
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jint, jstring, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addPolyline
 * Signature: ([Limgui/ImVec2;IIIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addPolyline
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addConvexPolyFilled
 * Signature: ([Limgui/ImVec2;II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addConvexPolyFilled
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addBezierCubic
 * Signature: (FFFFFFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addBezierCubic__FFFFFFFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addBezierCubic
 * Signature: (FFFFFFFFIFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addBezierCubic__FFFFFFFFIFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addBezierQuadratic
 * Signature: (FFFFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addBezierQuadratic__FFFFFFIF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addBezierQuadratic
 * Signature: (FFFFFFIFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addBezierQuadratic__FFFFFFIFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addImage
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addImage__IFFFF
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addImage
 * Signature: (IFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addImage__IFFFFFF
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addImage
 * Signature: (IFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addImage__IFFFFFFFF
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addImage
 * Signature: (IFFFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addImage__IFFFFFFFFI
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addImageQuad
 * Signature: (IFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addImageQuad__IFFFFFFFF
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addImageQuad
 * Signature: (IFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addImageQuad__IFFFFFFFFFF
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addImageQuad
 * Signature: (IFFFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addImageQuad__IFFFFFFFFFFFF
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addImageQuad
 * Signature: (IFFFFFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addImageQuad__IFFFFFFFFFFFFFF
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addImageQuad
 * Signature: (IFFFFFFFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addImageQuad__IFFFFFFFFFFFFFFFF
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addImageQuad
 * Signature: (IFFFFFFFFFFFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addImageQuad__IFFFFFFFFFFFFFFFFI
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    addImageRounded
 * Signature: (IFFFFFFFFIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addImageRounded__IFFFFFFFFIF
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    addImageRounded
 * Signature: (IFFFFFFFFIFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_addImageRounded__IFFFFFFFFIFI
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    pathClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pathClear
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    pathLineTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pathLineTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    pathLineToMergeDuplicate
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pathLineToMergeDuplicate
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    pathFillConvex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pathFillConvex
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    pathStroke
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pathStroke__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    pathStroke
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pathStroke__IIF
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    pathArcTo
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pathArcTo__FFFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    pathArcTo
 * Signature: (FFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pathArcTo__FFFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    pathArcToFast
 * Signature: (FFFII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pathArcToFast
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    pathBezierCubicCurveTo
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pathBezierCubicCurveTo__FFFFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    pathBezierCubicCurveTo
 * Signature: (FFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pathBezierCubicCurveTo__FFFFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    pathBezierQuadraticCurveTo
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pathBezierQuadraticCurveTo__FFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    pathBezierQuadraticCurveTo
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pathBezierQuadraticCurveTo__FFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    pathRect
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pathRect__FFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    pathRect
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pathRect__FFFFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImDrawList
 * Method:    pathRect
 * Signature: (FFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_pathRect__FFFFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    channelsSplit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_channelsSplit
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    channelsMerge
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_channelsMerge
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawList
 * Method:    channelsSetCurrent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_channelsSetCurrent
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    primReserve
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_primReserve
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    primUnreserve
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_primUnreserve
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    primRect
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_primRect
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    primRectUV
 * Signature: (FFFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_primRectUV
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    primQuadUV
 * Signature: (FFFFFFFFFFFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_primQuadUV
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    primWriteVtx
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_primWriteVtx
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     imgui_ImDrawList
 * Method:    primVtx
 * Signature: (FFFFI)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawList_primVtx
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
