/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_implot_ImPlotPoint */

#ifndef _Included_imgui_extension_implot_ImPlotPoint
#define _Included_imgui_extension_implot_ImPlotPoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_implot_ImPlotPoint
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlotPoint_create__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotPoint
 * Method:    create
 * Signature: (DD)J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlotPoint_create__DD
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     imgui_extension_implot_ImPlotPoint
 * Method:    getX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_imgui_extension_implot_ImPlotPoint_getX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotPoint
 * Method:    getY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_imgui_extension_implot_ImPlotPoint_getY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotPoint
 * Method:    setX
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotPoint_setX
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     imgui_extension_implot_ImPlotPoint
 * Method:    setY
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotPoint_setY
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
