/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_imnodes_ImNodesContext */

#ifndef _Included_imgui_extension_imnodes_ImNodesContext
#define _Included_imgui_extension_imnodes_ImNodesContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_imnodes_ImNodesContext
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_imnodes_ImNodesContext_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesContext
 * Method:    nDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesContext_nDestroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
