/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_nodeditor_NodeEditorStyle */

#ifndef _Included_imgui_extension_nodeditor_NodeEditorStyle
#define _Included_imgui_extension_nodeditor_NodeEditorStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getNodePadding
 * Signature: (Limgui/ImVec4;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getNodePadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setNodePadding
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setNodePadding
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getNodeRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getNodeRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setNodeRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setNodeRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getNodeBorderWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getNodeBorderWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setNodeBorderWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setNodeBorderWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getHoveredNodeBorderWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getHoveredNodeBorderWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setHoveredNodeBorderWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setHoveredNodeBorderWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getSelectedNodeBorderWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getSelectedNodeBorderWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setSelectedNodeBorderWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setSelectedNodeBorderWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getPinRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getPinRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setPinRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setPinRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getPinBorderWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getPinBorderWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setPinBorderWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setPinBorderWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getLinkStrength
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getLinkStrength
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setLinkStrength
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setLinkStrength
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getSourceDirection
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getSourceDirection
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getSourceDirectionX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getSourceDirectionX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getSourceDirectionY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getSourceDirectionY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setSourceDirection
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setSourceDirection
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getTargetDirection
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getTargetDirection
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getTargetDirectionX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getTargetDirectionX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getTargetDirectionY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getTargetDirectionY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setTargetDirection
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setTargetDirection
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getScrollDuration
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getScrollDuration
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setScrollDuration
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setScrollDuration
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getFlowMarkerDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getFlowMarkerDistance
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setFlowMarkerDistance
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setFlowMarkerDistance
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getFlowSpeed
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getFlowSpeed
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setFlowSpeed
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setFlowSpeed
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getFlowDuration
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getFlowDuration
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setFlowDuration
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setFlowDuration
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getPivotAlignment
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getPivotAlignment
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getPivotAlignmentX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getPivotAlignmentX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getPivotAlignmentY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getPivotAlignmentY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setPivotAlignment
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setPivotAlignment
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getPivotSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getPivotSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getPivotSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getPivotSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getPivotSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getPivotSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setPivotSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setPivotSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getPivotScale
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getPivotScale
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getPivotScaleX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getPivotScaleX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getPivotScaleY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getPivotScaleY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setPivotScale
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setPivotScale
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getPinCorners
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getPinCorners
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setPinCorners
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setPinCorners
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getPinRadius
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getPinRadius
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setPinRadius
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setPinRadius
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getPinArrowSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getPinArrowSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setPinArrowSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setPinArrowSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getPinArrowWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getPinArrowWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setPinArrowWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setPinArrowWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getGroupRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getGroupRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setGroupRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setGroupRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getGroupBorderWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getGroupBorderWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setGroupBorderWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setGroupBorderWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getColors
 * Signature: ([[F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getColors
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setColors
 * Signature: ([[F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setColors
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    getColor
 * Signature: (ILimgui/ImVec4;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_getColor
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setColor
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setColor__IFFFF
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setColor
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setColor__IIIII
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorStyle
 * Method:    setColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorStyle_setColor__II
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
