/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_nodeditor_NodeEditor */

#ifndef _Included_imgui_extension_nodeditor_NodeEditor
#define _Included_imgui_extension_nodeditor_NodeEditor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nSetCurrentEditor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_nSetCurrentEditor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    begin
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_begin
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    beginNode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_beginNode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    group
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_group
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    beginGroupHint
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_beginGroupHint
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    beginPin
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_beginPin
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    endGroupHint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_endGroupHint
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    endPin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_endPin
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    endNode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_endNode
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_end
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getScreenSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_getScreenSizeX
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getScreenSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_getScreenSizeY
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    toCanvasX
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_toCanvasX
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    toCanvasY
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_toCanvasY
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    toScreenX
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_toScreenX
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    toScreenY
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_toScreenY
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetStyle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetStyle
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getStyleColorName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_nodeditor_NodeEditor_getStyleColorName
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    pushStyleColor
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_pushStyleColor
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    popStyleColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_popStyleColor
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    pushStyleVar
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_pushStyleVar__IF
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    pushStyleVar
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_pushStyleVar__IFF
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    pushStyleVar
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_pushStyleVar__IFFFF
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    popStyleVar
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_popStyleVar
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getGroupMinX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_getGroupMinX
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getGroupMinY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_getGroupMinY
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getGroupMaxX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_getGroupMaxX
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getGroupMaxY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_getGroupMaxY
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetHintForegroundDrawList
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetHintForegroundDrawList
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetHintBackgroundDrawList
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetHintBackgroundDrawList
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nGetNodeBackgroundDrawList
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_nGetNodeBackgroundDrawList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getDoubleClickedNode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_getDoubleClickedNode
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getDoubleClickedPin
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_getDoubleClickedPin
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getDoubleClickedLink
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_getDoubleClickedLink
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    isBackgroundClicked
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_isBackgroundClicked
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    isBackgroundDoubleClicked
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_isBackgroundDoubleClicked
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    pinHadAnyLinks
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_pinHadAnyLinks
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getCurrentZoom
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_getCurrentZoom
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    pinRect
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_pinRect
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    pinPivotRect
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_pinPivotRect
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    pinPivotSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_pinPivotSize
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    pinPivotScale
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_pinPivotScale
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    pinPivotAlignment
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_pinPivotAlignment
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nShowNodeContextMenu
 * Signature: ([J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nShowNodeContextMenu
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nShowPinContextMenu
 * Signature: ([J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nShowPinContextMenu
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nShowLinkContextMenu
 * Signature: ([J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nShowLinkContextMenu
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getNodeWithContextMenu
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_getNodeWithContextMenu
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getPinWithContextMenu
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_getPinWithContextMenu
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getLinkWithContextMenu
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditor_getLinkWithContextMenu
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    showBackgroundContextMenu
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_showBackgroundContextMenu
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    restoreNodeState
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_restoreNodeState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    suspend
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_suspend
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    resume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_resume
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    isSuspended
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_isSuspended
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    isActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_isActive
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    setNodePosition
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_setNodePosition
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    link
 * Signature: (JJJFFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_link
  (JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    flow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_flow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    beginCreate
 * Signature: (FFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_beginCreate
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nQueryNewLink
 * Signature: ([J[JFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nQueryNewLink
  (JNIEnv *, jclass, jlongArray, jlongArray, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    acceptNewItem
 * Signature: (FFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_acceptNewItem
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    rejectNewItem
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_rejectNewItem
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    endCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_endCreate
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    beginDelete
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_beginDelete
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nQueryDeletedLink
 * Signature: ([J[J[J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nQueryDeletedLink
  (JNIEnv *, jclass, jlongArray, jlongArray, jlongArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    nQueryDeletedNode
 * Signature: ([J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_nQueryDeletedNode
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    acceptDeletedItem
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_acceptDeletedItem
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    rejectDeletedItem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_rejectDeletedItem
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    endDelete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_endDelete
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    navigateToContent
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_navigateToContent
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    navigateToSelection
 * Signature: (ZF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_navigateToSelection
  (JNIEnv *, jclass, jboolean, jfloat);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getNodePosition
 * Signature: (JLimgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_getNodePosition
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getNodePositionX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_getNodePositionX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getNodePositionY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_getNodePositionY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getNodeSizeX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_getNodeSizeX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getNodeSizeY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_nodeditor_NodeEditor_getNodeSizeY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    centerNodeOnScreen
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_centerNodeOnScreen
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    hasSelectionChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_hasSelectionChanged
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getSelectedObjectCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditor_getSelectedObjectCount
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getSelectedNodes
 * Signature: ([JI)I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditor_getSelectedNodes
  (JNIEnv *, jclass, jlongArray, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getSelectedLinks
 * Signature: ([JI)I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditor_getSelectedLinks
  (JNIEnv *, jclass, jlongArray, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    clearSelection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_clearSelection
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    selectNode
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_selectNode
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    selectLink
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_selectLink
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    deselectNode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_deselectNode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    deselectLink
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_deselectLink
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    deleteNode
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_deleteNode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    deleteLink
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_deleteLink
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    enableShortcuts
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_enableShortcuts
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    areShortcutsEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_areShortcutsEnabled
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    beginShortcut
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_beginShortcut
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    acceptCut
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_acceptCut
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    acceptCopy
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_acceptCopy
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    acceptPaste
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_acceptPaste
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    acceptDuplicate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_acceptDuplicate
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    acceptCreateNode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_nodeditor_NodeEditor_acceptCreateNode
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getActionContextSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditor_getActionContextSize
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getActionContextNodes
 * Signature: ([JI)I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditor_getActionContextNodes
  (JNIEnv *, jclass, jlongArray, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    getActionContextLinks
 * Signature: ([JI)I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_nodeditor_NodeEditor_getActionContextLinks
  (JNIEnv *, jclass, jlongArray, jint);

/*
 * Class:     imgui_extension_nodeditor_NodeEditor
 * Method:    endShortcut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditor_endShortcut
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
