/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiIO */

#ifndef _Included_imgui_ImGuiIO
#define _Included_imgui_ImGuiIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiIO
 * Method:    getConfigFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_getConfigFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setConfigFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setConfigFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getBackendFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_getBackendFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setBackendFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setBackendFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getIniSavingRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getIniSavingRate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setIniSavingRate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setIniSavingRate
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getIniFilename
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_ImGuiIO_getIniFilename
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setIniFilename
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setIniFilename
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getLogFilename
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_ImGuiIO_getLogFilename
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setLogFilename
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setLogFilename
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMouseDoubleClickTime
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getMouseDoubleClickTime
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setMouseDoubleClickTime
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setMouseDoubleClickTime
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMouseDoubleClickMaxDist
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getMouseDoubleClickMaxDist
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setMouseDoubleClickMaxDist
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setMouseDoubleClickMaxDist
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMouseDragThreshold
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getMouseDragThreshold
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setMouseDragThreshold
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setMouseDragThreshold
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getKeyMap
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_getKeyMap___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getKeyMap
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_getKeyMap__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setKeyMap
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setKeyMap__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setKeyMap
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setKeyMap___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getKeyRepeatDelay
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getKeyRepeatDelay
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setKeyRepeatDelay
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setKeyRepeatDelay
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getKeyRepeatRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getKeyRepeatRate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setKeyRepeatRate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setKeyRepeatRate
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nGetFonts
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiIO_nGetFonts
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetFonts
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetFonts
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getFontGlobalScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getFontGlobalScale
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setFontGlobalScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setFontGlobalScale
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getFontAllowUserScaling
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getFontAllowUserScaling
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setFontAllowUserScaling
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setFontAllowUserScaling
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    nSetFontDefault
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_nSetFontDefault
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMouseDrawCursor
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getMouseDrawCursor
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setMouseDrawCursor
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setMouseDrawCursor
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getConfigMacOSXBehaviors
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getConfigMacOSXBehaviors
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setConfigMacOSXBehaviors
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setConfigMacOSXBehaviors
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getConfigInputTextCursorBlink
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getConfigInputTextCursorBlink
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setConfigInputTextCursorBlink
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setConfigInputTextCursorBlink
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getConfigDragClickToInputText
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getConfigDragClickToInputText
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setConfigDragClickToInputText
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setConfigDragClickToInputText
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getConfigWindowsResizeFromEdges
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getConfigWindowsResizeFromEdges
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setConfigWindowsResizeFromEdges
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setConfigWindowsResizeFromEdges
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getConfigWindowsMoveFromTitleBarOnly
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getConfigWindowsMoveFromTitleBarOnly
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setConfigWindowsMoveFromTitleBarOnly
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setConfigWindowsMoveFromTitleBarOnly
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getConfigMemoryCompactTimer
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getConfigMemoryCompactTimer
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setConfigMemoryCompactTimer
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setConfigMemoryCompactTimer
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getBackendPlatformName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_ImGuiIO_getBackendPlatformName
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setBackendPlatformName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setBackendPlatformName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getBackendRendererName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_ImGuiIO_getBackendRendererName
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setBackendRendererName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setBackendRendererName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setSetClipboardTextFn
 * Signature: (Limgui/callback/ImStrConsumer;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setSetClipboardTextFn
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setGetClipboardTextFn
 * Signature: (Limgui/callback/ImStrSupplier;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setGetClipboardTextFn
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getDisplaySize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_getDisplaySize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getDisplaySizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getDisplaySizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getDisplaySizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getDisplaySizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setDisplaySize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setDisplaySize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getDisplayFramebufferScale
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_getDisplayFramebufferScale
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getDisplayFramebufferScaleX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getDisplayFramebufferScaleX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getDisplayFramebufferScaleY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getDisplayFramebufferScaleY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setDisplayFramebufferScale
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setDisplayFramebufferScale
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getConfigDockingNoSplit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getConfigDockingNoSplit
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setConfigDockingNoSplit
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setConfigDockingNoSplit
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getConfigDockingWithShift
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getConfigDockingWithShift
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setConfigDockingWithShift
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setConfigDockingWithShift
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getConfigDockingAlwaysTabBar
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getConfigDockingAlwaysTabBar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setConfigDockingAlwaysTabBar
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setConfigDockingAlwaysTabBar
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getConfigDockingTransparentPayload
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getConfigDockingTransparentPayload
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setConfigDockingTransparentPayload
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setConfigDockingTransparentPayload
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getConfigViewportsNoAutoMerge
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getConfigViewportsNoAutoMerge
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setConfigViewportsNoAutoMerge
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setConfigViewportsNoAutoMerge
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getConfigViewportsNoTaskBarIcon
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getConfigViewportsNoTaskBarIcon
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setConfigViewportsNoTaskBarIcon
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setConfigViewportsNoTaskBarIcon
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getConfigViewportsNoDecoration
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getConfigViewportsNoDecoration
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setConfigViewportsNoDecoration
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setConfigViewportsNoDecoration
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getConfigViewportsNoDefaultParent
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getConfigViewportsNoDefaultParent
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setConfigViewportsNoDefaultParent
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setConfigViewportsNoDefaultParent
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getDeltaTime
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getDeltaTime
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setDeltaTime
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setDeltaTime
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMousePos
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_getMousePos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMousePosX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getMousePosX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMousePosY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getMousePosY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setMousePos
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setMousePos
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMouseDown
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_getMouseDown___3Z
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMouseDown
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getMouseDown__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setMouseDown
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setMouseDown__IZ
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setMouseDown
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setMouseDown___3Z
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMouseWheel
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getMouseWheel
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setMouseWheel
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setMouseWheel
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMouseWheelH
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getMouseWheelH
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setMouseWheelH
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setMouseWheelH
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMouseHoveredViewport
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getMouseHoveredViewport
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setMouseHoveredViewport
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setMouseHoveredViewport
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getKeyCtrl
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getKeyCtrl
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setKeyCtrl
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setKeyCtrl
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getKeyShift
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getKeyShift
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setKeyShift
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setKeyShift
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getKeyAlt
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getKeyAlt
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setKeyAlt
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setKeyAlt
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getKeySuper
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getKeySuper
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setKeySuper
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setKeySuper
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getKeysDown
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_getKeysDown___3Z
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getKeysDown
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getKeysDown__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setKeysDown
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setKeysDown__IZ
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setKeysDown
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setKeysDown___3Z
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getNavInputs
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_getNavInputs___3F
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getNavInputs
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getNavInputs__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setNavInputs
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setNavInputs__IF
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setNavInputs
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setNavInputs___3F
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getWantCaptureMouse
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getWantCaptureMouse
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setWantCaptureMouse
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setWantCaptureMouse
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getWantCaptureKeyboard
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getWantCaptureKeyboard
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setWantCaptureKeyboard
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setWantCaptureKeyboard
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getWantTextInput
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getWantTextInput
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setWantTextInput
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setWantTextInput
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getWantSetMousePos
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getWantSetMousePos
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setWantSetMousePos
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setWantSetMousePos
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getWantSaveIniSettings
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getWantSaveIniSettings
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setWantSaveIniSettings
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setWantSaveIniSettings
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getNavActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getNavActive
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setNavActive
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setNavActive
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getNavVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiIO_getNavVisible
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setNavVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setNavVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getFramerate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getFramerate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setFramerate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setFramerate
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMetricsRenderVertices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_getMetricsRenderVertices
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setMetricsRenderVertices
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setMetricsRenderVertices
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMetricsRenderIndices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_getMetricsRenderIndices
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setMetricsRenderIndices
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setMetricsRenderIndices
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMetricsRenderWindows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_getMetricsRenderWindows
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setMetricsRenderWindows
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setMetricsRenderWindows
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMetricsActiveWindows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_getMetricsActiveWindows
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setMetricsActiveWindows
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setMetricsActiveWindows
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMetricsActiveAllocations
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiIO_getMetricsActiveAllocations
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setMetricsActiveAllocations
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setMetricsActiveAllocations
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMouseDelta
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_getMouseDelta
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMouseDeltaX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getMouseDeltaX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    getMouseDeltaY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiIO_getMouseDeltaY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    setMouseDelta
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_setMouseDelta
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiIO
 * Method:    addInputCharacter
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_addInputCharacter
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiIO
 * Method:    addInputCharacterUTF16
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_addInputCharacterUTF16
  (JNIEnv *, jobject, jshort);

/*
 * Class:     imgui_ImGuiIO
 * Method:    addInputCharactersUTF8
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_addInputCharactersUTF8
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiIO
 * Method:    addFocusEvent
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_addFocusEvent
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiIO
 * Method:    clearInputCharacters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_clearInputCharacters
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiIO
 * Method:    clearInputKeys
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiIO_clearInputKeys
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
