/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_imguiknobs_ImGuiKnobs */

#ifndef _Included_imgui_extension_imguiknobs_ImGuiKnobs
#define _Included_imgui_extension_imguiknobs_ImGuiKnobs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnob
 * Signature: (Ljava/lang/String;[FFFFLjava/lang/String;IFII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnob
  (JNIEnv *, jclass, jstring, jfloatArray, jfloat, jfloat, jfloat, jstring, jint, jfloat, jint, jint);

/*
 * Class:     imgui_extension_imguiknobs_ImGuiKnobs
 * Method:    nKnobInt
 * Signature: (Ljava/lang/String;[IIIFLjava/lang/String;IFII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imguiknobs_ImGuiKnobs_nKnobInt
  (JNIEnv *, jclass, jstring, jintArray, jint, jint, jfloat, jstring, jint, jfloat, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
