/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_imnodes_ImNodes */

#ifndef _Included_imgui_extension_imnodes_ImNodes
#define _Included_imgui_extension_imnodes_ImNodes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nEditorContextSet
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nEditorContextSet
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    createContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_createContext
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    destroyContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_destroyContext
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nGetStyle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_imnodes_ImNodes_nGetStyle
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    styleColorsDark
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_styleColorsDark
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    styleColorsClassic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_styleColorsClassic
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    styleColorsLight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_styleColorsLight
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    pushColorStyle
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_pushColorStyle
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    popColorStyle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_popColorStyle
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    pushStyleVar
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_pushStyleVar__IF
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    pushStyleVar
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_pushStyleVar__IFF
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    popStyleVar
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_popStyleVar
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    beginNodeEditor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_beginNodeEditor
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    endNodeEditor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_endNodeEditor
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    beginNode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_beginNode
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    endNode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_endNode
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    link
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_link
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    beginNodeTitleBar
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_beginNodeTitleBar
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    endNodeTitleBar
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_endNodeTitleBar
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    beginStaticAttribute
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_beginStaticAttribute
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    endStaticAttribute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_endStaticAttribute
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    beginInputAttribute
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_beginInputAttribute
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    endInputAttribute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_endInputAttribute
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    beginOutputAttribute
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_beginOutputAttribute
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    pushAttributeFlag
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_pushAttributeFlag
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    endOutputAttribute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_endOutputAttribute
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    isEditorHovered
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_isEditorHovered
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getHoveredNode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_imnodes_ImNodes_getHoveredNode
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getHoveredLink
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_imnodes_ImNodes_getHoveredLink
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getHoveredPin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_imnodes_ImNodes_getHoveredPin
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getActiveAttribute
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_imnodes_ImNodes_getActiveAttribute
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    isAttributeActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_isAttributeActive
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkStarted
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkStarted
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkDropped
 * Signature: ([IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkDropped
  (JNIEnv *, jclass, jintArray, jboolean);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkCreated
 * Signature: ([I[I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkCreated___3I_3I
  (JNIEnv *, jclass, jintArray, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkCreated
 * Signature: ([I[I[I[I[Z)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkCreated___3I_3I_3I_3I_3Z
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jintArray, jbooleanArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nIsLinkDestroyed
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_nIsLinkDestroyed
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    numSelectedNodes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_imnodes_ImNodes_numSelectedNodes
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    numSelectedLinks
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_imnodes_ImNodes_numSelectedLinks
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getSelectedNodes
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_getSelectedNodes
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getSelectedLinks
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_getSelectedLinks
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    clearNodeSelection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_clearNodeSelection__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    clearNodeSelection
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_clearNodeSelection__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    clearLinkSelection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_clearLinkSelection__
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    clearLinkSelection
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_clearLinkSelection__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    selectNode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_selectNode
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    selectLink
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_selectLink
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    isNodeSelected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_isNodeSelected
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    isLinkSelected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_imnodes_ImNodes_isLinkSelected
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    setNodeDraggable
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_setNodeDraggable
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getNodeDimensions
 * Signature: (ILimgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_getNodeDimensions
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getNodeDimensionsX
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_getNodeDimensionsX
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getNodeDimensionsY
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_getNodeDimensionsY
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    setNodeScreenSpacePos
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_setNodeScreenSpacePos
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    setNodeEditorSpacePos
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_setNodeEditorSpacePos
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    setNodeGridSpacePos
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_setNodeGridSpacePos
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getNodeScreenSpacePos
 * Signature: (ILimgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_getNodeScreenSpacePos
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getNodeScreenSpacePosX
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_getNodeScreenSpacePosX
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getNodeScreenSpacePosY
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_getNodeScreenSpacePosY
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getNodeEditorSpacePos
 * Signature: (ILimgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_getNodeEditorSpacePos
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getNodeEditorSpacePosX
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_getNodeEditorSpacePosX
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getNodeEditorSpacePosY
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_getNodeEditorSpacePosY
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getNodeGridSpacePos
 * Signature: (ILimgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_getNodeGridSpacePos
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getNodeGridSpacePosX
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_getNodeGridSpacePosX
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    getNodeGridSpacePosY
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodes_getNodeGridSpacePosY
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    editorResetPanning
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_editorResetPanning
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    editorContextGetPanning
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_editorContextGetPanning
  (JNIEnv *, jclass, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    editorMoveToNode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_editorMoveToNode
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    saveCurrentEditorStateToIniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_imnodes_ImNodes_saveCurrentEditorStateToIniString
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nSaveEditorStateToIniString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_imnodes_ImNodes_nSaveEditorStateToIniString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    loadCurrentEditorStateFromIniString
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_loadCurrentEditorStateFromIniString
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nLoadEditorStateFromIniString
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nLoadEditorStateFromIniString
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    saveCurrentEditorStateToIniFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_saveCurrentEditorStateToIniFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nSaveEditorStateToIniFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nSaveEditorStateToIniFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    loadCurrentEditorStateFromIniFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_loadCurrentEditorStateFromIniFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    nLoadEditorStateFromIniFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_nLoadEditorStateFromIniFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     imgui_extension_imnodes_ImNodes
 * Method:    miniMap
 * Signature: (FI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodes_miniMap
  (JNIEnv *, jclass, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
