/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiTextFilter */

#ifndef _Included_imgui_ImGuiTextFilter
#define _Included_imgui_ImGuiTextFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    nCreate
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiTextFilter_nCreate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    draw
 * Signature: (Ljava/lang/String;F)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiTextFilter_draw
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    passFilter
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiTextFilter_passFilter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    build
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiTextFilter_build
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiTextFilter_clear
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    isActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiTextFilter_isActive
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    getInputBuffer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_ImGuiTextFilter_getInputBuffer
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiTextFilter
 * Method:    setInputBuffer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiTextFilter_setInputBuffer
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
