/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiViewport */

#ifndef _Included_imgui_ImGuiViewport
#define _Included_imgui_ImGuiViewport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiViewport
 * Method:    getID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiViewport_getID
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setID
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiViewport_getFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getPos
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_getPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getPosX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_getPosX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getPosY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_getPosY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setPos
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setPos
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_getSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_getSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_getSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    seSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_seSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getWorkPos
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_getWorkPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getWorkPosX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_getWorkPosX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getWorkPosY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_getWorkPosY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setWorkPos
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setWorkPos
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getWorkSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_getWorkSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getWorkSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_getWorkSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getWorkSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_getWorkSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setWorkSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setWorkSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getDpiScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_getDpiScale
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setDpiScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setDpiScale
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getParentViewportId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiViewport_getParentViewportId
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setParentViewportId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setParentViewportId
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    nGetDrawData
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiViewport_nGetDrawData
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setRendererUserData
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setRendererUserData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getRendererUserData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_imgui_ImGuiViewport_getRendererUserData
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setPlatformUserData
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setPlatformUserData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getPlatformUserData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_imgui_ImGuiViewport_getPlatformUserData
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setPlatformHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setPlatformHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getPlatformHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiViewport_getPlatformHandle
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setPlatformHandleRaw
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setPlatformHandleRaw
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getPlatformHandleRaw
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiViewport_getPlatformHandleRaw
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getPlatformRequestMove
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiViewport_getPlatformRequestMove
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setPlatformRequestMove
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setPlatformRequestMove
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getPlatformRequestResize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiViewport_getPlatformRequestResize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setPlatformRequestResize
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setPlatformRequestResize
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getPlatformRequestClose
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiViewport_getPlatformRequestClose
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    setPlatformRequestClose
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_setPlatformRequestClose
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getCenter
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_getCenter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getCenterX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_getCenterX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getCenterY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_getCenterY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getWorkCenter
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiViewport_getWorkCenter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getWorkCenterX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_getWorkCenterX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiViewport
 * Method:    getWorkCenterY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiViewport_getWorkCenterY
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
