/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImFontGlyph */

#ifndef _Included_imgui_ImFontGlyph
#define _Included_imgui_ImFontGlyph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImFontGlyph
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontGlyph_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    getColored
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontGlyph_getColored
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    setColored
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_setColored
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    getVisible
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontGlyph_getVisible
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    setVisible
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_setVisible
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    getCodepoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontGlyph_getCodepoint
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    setCodepoint
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_setCodepoint
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    getAdvanceX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_getAdvanceX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    setAdvanceX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_setAdvanceX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    getX0
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_getX0
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    setX0
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_setX0
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    getY0
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_getY0
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    setY0
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_setY0
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    getX1
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_getX1
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    setX1
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_setX1
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    getY1
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_getY1
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    setY1
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_setY1
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    getU0
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_getU0
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    setU0
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_setU0
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    getV0
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_getV0
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    setV0
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_setV0
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    getU1
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_getU1
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    setU1
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_setU1
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    getV1
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontGlyph_getV1
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontGlyph
 * Method:    setV1
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontGlyph_setV1
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
