/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_implot_ImPlot */

#ifndef _Included_imgui_extension_implot_ImPlot
#define _Included_imgui_extension_implot_ImPlot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nCreateContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlot_nCreateContext
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nDestroyContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nDestroyContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nGetCurrentContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlot_nGetCurrentContext
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nSetCurrentContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nSetCurrentContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    beginPlot
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_beginPlot__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    beginPlot
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_beginPlot__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nBeginPlot
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;FF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_nBeginPlot__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2FF
  (JNIEnv *, jclass, jstring, jstring, jstring, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nBeginPlot
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;FFIII)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_nBeginPlot__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2FFIII
  (JNIEnv *, jclass, jstring, jstring, jstring, jfloat, jfloat, jint, jint, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nBeginPlot
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;FFIIIIILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_nBeginPlot__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2FFIIIIILjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring, jstring, jfloat, jfloat, jint, jint, jint, jint, jint, jstring, jstring);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    endPlot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_endPlot
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotLine
 * Signature: (Ljava/lang/String;[D[DII)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPlotLine
  (JNIEnv *, jclass, jstring, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotScatter
 * Signature: (Ljava/lang/String;[D[DII)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPlotScatter
  (JNIEnv *, jclass, jstring, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotStairs
 * Signature: (Ljava/lang/String;[D[DII)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPlotStairs
  (JNIEnv *, jclass, jstring, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotShaded
 * Signature: (Ljava/lang/String;[D[DIII)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPlotShaded__Ljava_lang_String_2_3D_3DIII
  (JNIEnv *, jclass, jstring, jdoubleArray, jdoubleArray, jint, jint, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotShaded
 * Signature: (Ljava/lang/String;[D[D[DII)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPlotShaded__Ljava_lang_String_2_3D_3D_3DII
  (JNIEnv *, jclass, jstring, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotBars
 * Signature: (Ljava/lang/String;[D[DIFI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPlotBars
  (JNIEnv *, jclass, jstring, jdoubleArray, jdoubleArray, jint, jfloat, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotBarsH
 * Signature: (Ljava/lang/String;[D[DIFI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPlotBarsH
  (JNIEnv *, jclass, jstring, jdoubleArray, jdoubleArray, jint, jfloat, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotErrorBars
 * Signature: (Ljava/lang/String;[D[D[DII)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPlotErrorBars
  (JNIEnv *, jclass, jstring, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotErrorBarsH
 * Signature: (Ljava/lang/String;[D[D[DII)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPlotErrorBarsH
  (JNIEnv *, jclass, jstring, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotStems
 * Signature: (Ljava/lang/String;[DIII)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPlotStems
  (JNIEnv *, jclass, jstring, jdoubleArray, jint, jint, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotVLines
 * Signature: (Ljava/lang/String;[DII)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPlotVLines
  (JNIEnv *, jclass, jstring, jdoubleArray, jint, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotHLines
 * Signature: (Ljava/lang/String;[DII)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPlotHLines
  (JNIEnv *, jclass, jstring, jdoubleArray, jint, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotPieChart
 * Signature: (Ljava/lang/String;I[DIDDD)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPlotPieChart
  (JNIEnv *, jclass, jstring, jint, jdoubleArray, jint, jdouble, jdouble, jdouble);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotHeatmap
 * Signature: (Ljava/lang/String;[DII)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPlotHeatmap
  (JNIEnv *, jclass, jstring, jdoubleArray, jint, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotHistogram
 * Signature: (Ljava/lang/String;[DI)D
 */
JNIEXPORT jdouble JNICALL Java_imgui_extension_implot_ImPlot_nPlotHistogram
  (JNIEnv *, jclass, jstring, jdoubleArray, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotHistogram2D
 * Signature: (Ljava/lang/String;[D[DI)D
 */
JNIEXPORT jdouble JNICALL Java_imgui_extension_implot_ImPlot_nPlotHistogram2D
  (JNIEnv *, jclass, jstring, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotDigital
 * Signature: (Ljava/lang/String;[D[DI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPlotDigital
  (JNIEnv *, jclass, jstring, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    plotText
 * Signature: (Ljava/lang/String;DDZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_plotText
  (JNIEnv *, jclass, jstring, jdouble, jdouble, jboolean);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    plotDummy
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_plotDummy
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    setNextPlotLimits
 * Signature: (DDDDI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_setNextPlotLimits
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    setNextPlotLimitsX
 * Signature: (DDI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_setNextPlotLimitsX
  (JNIEnv *, jclass, jdouble, jdouble, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    setNextPlotLimitsY
 * Signature: (DDI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_setNextPlotLimitsY
  (JNIEnv *, jclass, jdouble, jdouble, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nLinkNextPlotLimits
 * Signature: ([D[D[D[D[D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nLinkNextPlotLimits
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    fitNextPlotAxes
 * Signature: (ZZZZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_fitNextPlotAxes
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nSetNextPlotTicksX
 * Signature: (DDILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nSetNextPlotTicksX
  (JNIEnv *, jclass, jdouble, jdouble, jint, jstring, jstring, jstring, jstring, jboolean);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nSetNextPlotTicksY
 * Signature: (DDILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nSetNextPlotTicksY
  (JNIEnv *, jclass, jdouble, jdouble, jint, jstring, jstring, jstring, jstring, jboolean, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    setNextPlotFormatX
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_setNextPlotFormatX
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    setNextPlotFormatY
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_setNextPlotFormatY
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    setPlotYAxis
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_setPlotYAxis
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    hideNextItem
 * Signature: (ZI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_hideNextItem
  (JNIEnv *, jclass, jboolean, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPixelsToPlot
 * Signature: (FFI)J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlot_nPixelsToPlot
  (JNIEnv *, jclass, jfloat, jfloat, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPlotToPixels
 * Signature: (DDILimgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPlotToPixels
  (JNIEnv *, jclass, jdouble, jdouble, jint, jobject);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    getPlotPos
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_getPlotPos
  (JNIEnv *, jclass, jobject);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    getPlotSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_getPlotSize
  (JNIEnv *, jclass, jobject);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    isPlotHovered
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_isPlotHovered
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    isPlotXAxisHovered
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_isPlotXAxisHovered
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    isPlotYAxisHovered
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_isPlotYAxisHovered
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nGetPlotMousePos
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlot_nGetPlotMousePos
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nGetPlotLimits
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlot_nGetPlotLimits
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    isPlotSelected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_isPlotSelected
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nGetPlotSelection
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlot_nGetPlotSelection
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    isPlotQueried
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_isPlotQueried
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nGetPlotQuery
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlot_nGetPlotQuery
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nSetPlotQuery
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nSetPlotQuery
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nAnnotate
 * Signature: (DDFFFFFFLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nAnnotate
  (JNIEnv *, jclass, jdouble, jdouble, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nAnnotateClamped
 * Signature: (DDFFFFFFLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nAnnotateClamped
  (JNIEnv *, jclass, jdouble, jdouble, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nDragLineX
 * Signature: (Ljava/lang/String;DZFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_nDragLineX
  (JNIEnv *, jclass, jstring, jdouble, jboolean, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nDragLineY
 * Signature: (Ljava/lang/String;DZFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_nDragLineY
  (JNIEnv *, jclass, jstring, jdouble, jboolean, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nDragPoint
 * Signature: (Ljava/lang/String;DDZFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_nDragPoint
  (JNIEnv *, jclass, jstring, jdouble, jdouble, jboolean, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    setLegendLocation
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_setLegendLocation
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    setMousePosLocation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_setMousePosLocation
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    isLegendEntryHovered
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_isLegendEntryHovered
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    beginLegendPopup
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_beginLegendPopup
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    endLegendPopup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_endLegendPopup
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    beginDragDropTarget
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_beginDragDropTarget
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    beginDragDropTargetX
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_beginDragDropTargetX
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    beginDragDropTargetY
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_beginDragDropTargetY
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    beginDragDropTargetLegend
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_beginDragDropTargetLegend
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    endDragDropTarget
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_endDragDropTarget
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    beginDragDropSource
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_beginDragDropSource
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    beginDragDropSourceX
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_beginDragDropSourceX
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    beginDragDropSourceY
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_beginDragDropSourceY
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    beginDragDropSourceItem
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_beginDragDropSourceItem
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    endDragDropSource
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_endDragDropSource
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nGetStyle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlot_nGetStyle
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    styleColorsAuto
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_styleColorsAuto
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    styleColorsClassic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_styleColorsClassic
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    styleColorsDark
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_styleColorsDark
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    styleColorsLight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_styleColorsLight
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    pushStyleColor
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_pushStyleColor
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPushStyleColor
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPushStyleColor
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    popStyleColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_popStyleColor
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    pushStyleVar
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_pushStyleVar__IF
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    pushStyleVar
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_pushStyleVar__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nPushStyleVar
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nPushStyleVar
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    popStyleVar
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_popStyleVar
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nGetLastItemColorS
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_implot_ImPlot_nGetLastItemColorS
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    getStyleColorName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_implot_ImPlot_getStyleColorName
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    getMarkerName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_implot_ImPlot_getMarkerName
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nAddColormap
 * Signature: (Ljava/lang/String;[F[F[F[FI)I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlot_nAddColormap
  (JNIEnv *, jclass, jstring, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    getColormapCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlot_getColormapCount
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    getColormapName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_extension_implot_ImPlot_getColormapName
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    getColormapIndex
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlot_getColormapIndex
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    pushColormap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_pushColormap__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    pushColormap
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_pushColormap__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    popColormap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_popColormap
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nNextColormapColor
 * Signature: (Limgui/ImVec4;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nNextColormapColor
  (JNIEnv *, jclass, jobject);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    getColormapSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_implot_ImPlot_getColormapSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nGetColormapColor
 * Signature: (IILimgui/ImVec4;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nGetColormapColor
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nSampleColormap
 * Signature: (FILimgui/ImVec4;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nSampleColormap
  (JNIEnv *, jclass, jfloat, jint, jobject);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    colormapScale
 * Signature: (Ljava/lang/String;DDI)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_colormapScale
  (JNIEnv *, jclass, jstring, jdouble, jdouble, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    colormapSlider
 * Signature: (Ljava/lang/String;FI)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_colormapSlider
  (JNIEnv *, jclass, jstring, jfloat, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    colormapButton
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_colormapButton
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    bustColorCache
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_bustColorCache
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nItemIcon
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nItemIcon
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    colormapIcon
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_colormapIcon
  (JNIEnv *, jclass, jint);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nGetPlotDrawList
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlot_nGetPlotDrawList
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    pushPlotClipRect
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_pushPlotClipRect
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    popPlotClipRect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_popPlotClipRect
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    showStyleSelector
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_showStyleSelector
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    showColormapSelector
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlot_showColormapSelector
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    showStyleEditor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_showStyleEditor
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    showUserGuide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_showUserGuide
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    showMetricsWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_showMetricsWindow
  (JNIEnv *, jclass);

/*
 * Class:     imgui_extension_implot_ImPlot
 * Method:    nShowDemoWindow
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlot_nShowDemoWindow
  (JNIEnv *, jclass, jbooleanArray);

#ifdef __cplusplus
}
#endif
#endif
