/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_memedit_MemoryEditorSizes */

#ifndef _Included_imgui_extension_memedit_MemoryEditorSizes
#define _Included_imgui_extension_memedit_MemoryEditorSizes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    setAddrDigitsCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_setAddrDigitsCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    getAddrDigitsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_getAddrDigitsCount
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    setLineHeight
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_setLineHeight
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    getLineHeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_getLineHeight
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    setGlyphWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_setGlyphWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    getGlyphWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_getGlyphWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    setHexCellWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_setHexCellWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    getHexCellWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_getHexCellWidth
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    setSpacingBetweenMidCols
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_setSpacingBetweenMidCols
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    getSpacingBetweenMidCols
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_getSpacingBetweenMidCols
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    setPosHexStart
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_setPosHexStart
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    getPosHexStart
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_getPosHexStart
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    setPosHexEnd
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_setPosHexEnd
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    getPosHexEnd
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_getPosHexEnd
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    setPosAsciiStart
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_setPosAsciiStart
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    getPosAsciiStart
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_getPosAsciiStart
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    setPosAsciiEnd
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_setPosAsciiEnd
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    getPosAsciiEnd
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_getPosAsciiEnd
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    setWindowWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_setWindowWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_memedit_MemoryEditorSizes
 * Method:    getWindowWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_memedit_MemoryEditorSizes_getWindowWidth
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
