/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_memedit_MemoryEditor */

#ifndef _Included_imgui_extension_memedit_MemoryEditor
#define _Included_imgui_extension_memedit_MemoryEditor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_memedit_MemoryEditor_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    gotoAddrAndHighlight
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_gotoAddrAndHighlight
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nCalcSizes
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nCalcSizes
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    drawWindow
 * Signature: (Ljava/lang/String;JJJ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_drawWindow
  (JNIEnv *, jobject, jstring, jlong, jlong, jlong);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    drawContents
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_drawContents
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nDrawOptionsLine
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nDrawOptionsLine
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     imgui_extension_memedit_MemoryEditor
 * Method:    nDrawPreviewLine
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_memedit_MemoryEditor_nDrawPreviewLine
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
