/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImFontConfig */

#ifndef _Included_imgui_ImFontConfig
#define _Included_imgui_ImFontConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImFontConfig
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImFontConfig_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getFontData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_imgui_ImFontConfig_getFontData
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setFontData
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setFontData
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getFontDataSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontConfig_getFontDataSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setFontDataSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setFontDataSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getFontDataOwnedByAtlas
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImFontConfig_getFontDataOwnedByAtlas
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setFontDataOwnedByAtlas
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setFontDataOwnedByAtlas
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getFontNo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontConfig_getFontNo
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setFontNo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setFontNo
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getSizePixels
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontConfig_getSizePixels
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setSizePixels
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setSizePixels
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getOversampleH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontConfig_getOversampleH
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setOversampleH
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setOversampleH
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getOversampleV
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontConfig_getOversampleV
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setOversampleV
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setOversampleV
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getPixelSnapH
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImFontConfig_getPixelSnapH
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setPixelSnapH
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setPixelSnapH
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getGlyphExtraSpacing
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_getGlyphExtraSpacing
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getGlyphExtraSpacingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontConfig_getGlyphExtraSpacingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getGlyphExtraSpacingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontConfig_getGlyphExtraSpacingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setGlyphExtraSpacing
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setGlyphExtraSpacing
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getGlyphOffset
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_getGlyphOffset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getGlyphOffsetX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontConfig_getGlyphOffsetX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getGlyphOffsetY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontConfig_getGlyphOffsetY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setGlyphOffset
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setGlyphOffset
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImFontConfig
 * Method:    nSetGlyphRanges
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_nSetGlyphRanges
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getGlyphMinAdvanceX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontConfig_getGlyphMinAdvanceX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setGlyphMinAdvanceX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setGlyphMinAdvanceX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getGlyphMaxAdvanceX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontConfig_getGlyphMaxAdvanceX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setGlyphMaxAdvanceX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setGlyphMaxAdvanceX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getMergeMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImFontConfig_getMergeMode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setMergeMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setMergeMode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getFontBuilderFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImFontConfig_getFontBuilderFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setFontBuilderFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setFontBuilderFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getRasterizerMultiply
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImFontConfig_getRasterizerMultiply
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setRasterizerMultiply
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setRasterizerMultiply
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImFontConfig
 * Method:    getEllipsisChar
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_imgui_ImFontConfig_getEllipsisChar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setEllipsisChar
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setEllipsisChar
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImFontConfig
 * Method:    setName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImFontConfig_setName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
