/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_implot_ImPlotLimits */

#ifndef _Included_imgui_extension_implot_ImPlotLimits
#define _Included_imgui_extension_implot_ImPlotLimits
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_implot_ImPlotLimits
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlotLimits_create__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotLimits
 * Method:    create
 * Signature: (DDDD)J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlotLimits_create__DDDD
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     imgui_extension_implot_ImPlotLimits
 * Method:    contains
 * Signature: (DD)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_extension_implot_ImPlotLimits_contains
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     imgui_extension_implot_ImPlotLimits
 * Method:    nMin
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlotLimits_nMin
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotLimits
 * Method:    nMax
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlotLimits_nMax
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_implot_ImPlotLimits
 * Method:    nGetX
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlotLimits_nGetX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_extension_implot_ImPlotLimits
 * Method:    nGetY
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_implot_ImPlotLimits_nGetY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_extension_implot_ImPlotLimits
 * Method:    nSetX
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotLimits_nSetX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_extension_implot_ImPlotLimits
 * Method:    nSetY
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_implot_ImPlotLimits_nSetY
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
