/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiInputTextCallbackData */

#ifndef _Included_imgui_ImGuiInputTextCallbackData
#define _Included_imgui_ImGuiInputTextCallbackData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    getEventFlag
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiInputTextCallbackData_getEventFlag
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    getFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiInputTextCallbackData_getFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    getEventChar
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiInputTextCallbackData_getEventChar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    setEventChar
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_setEventChar
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    getEventKey
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiInputTextCallbackData_getEventKey
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    getBuf
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imgui_ImGuiInputTextCallbackData_getBuf
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    getBufDirty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiInputTextCallbackData_getBufDirty
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    setBufDirty
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_setBufDirty
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    getCursorPos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiInputTextCallbackData_getCursorPos
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    setCursorPos
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_setCursorPos
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    getSelectionStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiInputTextCallbackData_getSelectionStart
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    setSelectionStart
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_setSelectionStart
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    getSelectionEnd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiInputTextCallbackData_getSelectionEnd
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    setSelectionEnd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_setSelectionEnd
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    deleteChars
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_deleteChars
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImGuiInputTextCallbackData
 * Method:    insertChars
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiInputTextCallbackData_insertChars
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
