/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_nodeditor_NodeEditorContext */

#ifndef _Included_imgui_extension_nodeditor_NodeEditorContext
#define _Included_imgui_extension_nodeditor_NodeEditorContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_nodeditor_NodeEditorContext
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditorContext_nCreate__
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorContext
 * Method:    nCreate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_imgui_extension_nodeditor_NodeEditorContext_nCreate__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_extension_nodeditor_NodeEditorContext
 * Method:    nDestroyEditorContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_extension_nodeditor_NodeEditorContext_nDestroyEditorContext
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
