/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiStyle */

#ifndef _Included_imgui_ImGuiStyle
#define _Included_imgui_ImGuiStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiStyle
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiStyle_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getAlpha
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getAlpha
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setAlpha
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setAlpha
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getDisabledAlpha
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getDisabledAlpha
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setDisabledAlpha
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setDisabledAlpha
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getWindowPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_getWindowPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getWindowPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getWindowPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getWindowPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getWindowPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setWindowPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setWindowPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getWindowRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getWindowRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setWindowRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setWindowRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getWindowBorderSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getWindowBorderSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setWindowBorderSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setWindowBorderSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getWindowMinSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_getWindowMinSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getWindowMinSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getWindowMinSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getWindowMinSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getWindowMinSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setWindowMinSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setWindowMinSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getWindowTitleAlign
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_getWindowTitleAlign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getWindowTitleAlignX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getWindowTitleAlignX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getWindowTitleAlignY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getWindowTitleAlignY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setWindowTitleAlign
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setWindowTitleAlign
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getWindowMenuButtonPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiStyle_getWindowMenuButtonPosition
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setWindowMenuButtonPosition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setWindowMenuButtonPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getChildRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getChildRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setChildRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setChildRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getChildBorderSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getChildBorderSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setChildBorderSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setChildBorderSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getPopupRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getPopupRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setPopupRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setPopupRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getPopupBorderSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getPopupBorderSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setPopupBorderSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setPopupBorderSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getFramePadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_getFramePadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getFramePaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getFramePaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getFramePaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getFramePaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setFramePadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setFramePadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getFrameRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getFrameRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setFrameRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setFrameRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getFrameBorderSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getFrameBorderSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setFrameBorderSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setFrameBorderSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getItemSpacing
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_getItemSpacing
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getItemSpacingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getItemSpacingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getItemSpacingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getItemSpacingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setItemSpacing
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setItemSpacing
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getItemInnerSpacing
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_getItemInnerSpacing
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getItemInnerSpacingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getItemInnerSpacingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getItemInnerSpacingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getItemInnerSpacingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setItemInnerSpacing
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setItemInnerSpacing
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getCellPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_getCellPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getCellPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getCellPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getCellPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getCellPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setCellPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setCellPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getTouchExtraPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_getTouchExtraPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getTouchExtraPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getTouchExtraPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getTouchExtraPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getTouchExtraPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setTouchExtraPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setTouchExtraPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getIndentSpacing
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getIndentSpacing
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setIndentSpacing
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setIndentSpacing
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getColumnsMinSpacing
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getColumnsMinSpacing
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setColumnsMinSpacing
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setColumnsMinSpacing
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getScrollbarSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getScrollbarSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setScrollbarSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setScrollbarSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getScrollbarRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getScrollbarRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setScrollbarRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setScrollbarRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getGrabMinSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getGrabMinSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setGrabMinSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setGrabMinSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getGrabRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getGrabRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setGrabRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setGrabRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getLogSliderDeadzone
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getLogSliderDeadzone
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setLogSliderDeadzone
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setLogSliderDeadzone
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getTabRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getTabRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setTabRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setTabRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getTabBorderSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getTabBorderSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setTabBorderSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setTabBorderSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getTabMinWidthForCloseButton
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getTabMinWidthForCloseButton
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setTabMinWidthForCloseButton
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setTabMinWidthForCloseButton
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getColorButtonPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiStyle_getColorButtonPosition
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setColorButtonPosition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setColorButtonPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getButtonTextAlign
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_getButtonTextAlign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getButtonTextAlignX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getButtonTextAlignX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getButtonTextAlignY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getButtonTextAlignY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setButtonTextAlign
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setButtonTextAlign
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getSelectableTextAlign
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_getSelectableTextAlign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getSelectableTextAlignX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getSelectableTextAlignX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getSelectableTextAlignY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getSelectableTextAlignY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setSelectableTextAlign
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setSelectableTextAlign
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getDisplayWindowPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_getDisplayWindowPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getDisplayWindowPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getDisplayWindowPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getDisplayWindowPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getDisplayWindowPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setDisplayWindowPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setDisplayWindowPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getDisplaySafeAreaPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_getDisplaySafeAreaPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getDisplaySafeAreaPaddingX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getDisplaySafeAreaPaddingX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getDisplaySafeAreaPaddingY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getDisplaySafeAreaPaddingY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setDisplaySafeAreaPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setDisplaySafeAreaPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getMouseCursorScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getMouseCursorScale
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setMouseCursorScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setMouseCursorScale
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getAntiAliasedLines
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiStyle_getAntiAliasedLines
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setAntiAliasedLines
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setAntiAliasedLines
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getAntiAliasedLinesUseTex
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiStyle_getAntiAliasedLinesUseTex
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setAntiAliasedLinesUseTex
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setAntiAliasedLinesUseTex
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getAntiAliasedFill
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiStyle_getAntiAliasedFill
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setAntiAliasedFill
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setAntiAliasedFill
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getCurveTessellationTol
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getCurveTessellationTol
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setCurveTessellationTol
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setCurveTessellationTol
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getCircleTessellationMaxError
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStyle_getCircleTessellationMaxError
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setCircleTessellationMaxError
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setCircleTessellationMaxError
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getColors
 * Signature: ([[F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_getColors
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setColors
 * Signature: ([[F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setColors
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    getColor
 * Signature: (ILimgui/ImVec4;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_getColor
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setColor
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setColor__IFFFF
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setColor
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setColor__IIIII
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    setColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_setColor__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImGuiStyle
 * Method:    scaleAllSizes
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStyle_scaleAllSizes
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
