/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiPlatformMonitor */

#ifndef _Included_imgui_ImGuiPlatformMonitor
#define _Included_imgui_ImGuiPlatformMonitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    getMainPos
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_getMainPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    getMainPosX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_getMainPosX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    getMainPosY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_getMainPosY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    setMainPos
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_setMainPos
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    getMainSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_getMainSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    getMainSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_getMainSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    getMainSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_getMainSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    setMainSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_setMainSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    getWorkPos
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_getWorkPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    getWorkPosX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_getWorkPosX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    getWorkPosY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_getWorkPosY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    setWorkPos
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_setWorkPos
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    getWorkSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_getWorkSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    getWorkSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_getWorkSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    getWorkSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_getWorkSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    setWorkSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_setWorkSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    getDpiScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiPlatformMonitor_getDpiScale
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiPlatformMonitor
 * Method:    setDpiScale
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiPlatformMonitor_setDpiScale
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
