/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_internal_ImGuiDockNode */

#ifndef _Included_imgui_internal_ImGuiDockNode
#define _Included_imgui_internal_ImGuiDockNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_getID
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setID
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getSharedFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_getSharedFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setSharedFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setSharedFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getLocalFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_getLocalFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setLocalFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setLocalFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getLocalFlagsInWindows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_getLocalFlagsInWindows
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setLocalFlagsInWindows
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setLocalFlagsInWindows
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getMergedFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_getMergedFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetParentNode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGuiDockNode_nGetParentNode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetParentNode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetParentNode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetChildNodeFirst
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGuiDockNode_nGetChildNodeFirst
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetChildNodeFirst
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetChildNodeFirst
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetChildNodeSecond
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGuiDockNode_nGetChildNodeSecond
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetChildNodeSecond
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetChildNodeSecond
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetWindowClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGuiDockNode_nGetWindowClass
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetWindowClass
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetWindowClass
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getPos
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_getPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getPosX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGuiDockNode_getPosX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getPosY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGuiDockNode_getPosY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setPos
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setPos
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getSize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_getSize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getSizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGuiDockNode_getSizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getSizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGuiDockNode_getSizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getSizeRef
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_getSizeRef
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getSizeRefX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGuiDockNode_getSizeRefX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getSizeRefY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_internal_ImGuiDockNode_getSizeRefY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setSizeRef
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setSizeRef
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getSplitAxis
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_getSplitAxis
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setSplitAxis
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setSplitAxis
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_getState
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setState
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetCentralNode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGuiDockNode_nGetCentralNode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetCentralNode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetCentralNode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nGetOnlyNodeWithWindows
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_internal_ImGuiDockNode_nGetOnlyNodeWithWindows
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nSetOnlyNodeWithWindows
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nSetOnlyNodeWithWindows
  (JNIEnv *, jobject, jlong);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getLastFrameAlive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_getLastFrameAlive
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setLastFrameAlive
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setLastFrameAlive
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getLastFrameActive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_getLastFrameActive
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setLastFrameActive
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setLastFrameActive
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getLastFrameFocused
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_getLastFrameFocused
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setLastFrameFocused
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setLastFrameFocused
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getLastFocusedNodeId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_getLastFocusedNodeId
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setLastFocusedNodeId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setLastFocusedNodeId
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getSelectedTabId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_getSelectedTabId
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setSelectedTabId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setSelectedTabId
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getWantCloseTabId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_getWantCloseTabId
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setWantCloseTabId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setWantCloseTabId
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getAuthorityForPos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_getAuthorityForPos
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setAuthorityForPos
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setAuthorityForPos
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getAuthorityForSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_getAuthorityForSize
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setAuthorityForSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setAuthorityForSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getAuthorityForViewport
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_internal_ImGuiDockNode_getAuthorityForViewport
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setAuthorityForViewport
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setAuthorityForViewport
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getIsVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_getIsVisible
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setIsVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setIsVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getIsFocused
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_getIsFocused
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setIsFocused
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setIsFocused
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getHasCloseButton
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_getHasCloseButton
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setHasCloseButton
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setHasCloseButton
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getHasWindowMenuButton
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_getHasWindowMenuButton
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setHasWindowMenuButton
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setHasWindowMenuButton
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getWantCloseAll
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_getWantCloseAll
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setWantCloseAll
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setWantCloseAll
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getWantLockSizeOnce
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_getWantLockSizeOnce
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setWantLockSizeOnce
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setWantLockSizeOnce
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getWantMouseMove
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_getWantMouseMove
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setWantMouseMove
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setWantMouseMove
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getWantHiddenTabBarUpdate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_getWantHiddenTabBarUpdate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setWantHiddenTabBarUpdate
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setWantHiddenTabBarUpdate
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    getWantHiddenTabBarToggle
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_getWantHiddenTabBarToggle
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    setWantHiddenTabBarToggle
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_setWantHiddenTabBarToggle
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    isRootNode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_isRootNode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    isDockSpace
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_isDockSpace
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    isFloatingNode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_isFloatingNode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    isCentralNode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_isCentralNode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    isHiddenTabBar
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_isHiddenTabBar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    isNoTabBar
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_isNoTabBar
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    isSplitNode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_isSplitNode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    isLeafNode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_isLeafNode
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    isEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_internal_ImGuiDockNode_isEmpty
  (JNIEnv *, jobject);

/*
 * Class:     imgui_internal_ImGuiDockNode
 * Method:    nRect
 * Signature: (Limgui/ImVec2;Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_internal_ImGuiDockNode_nRect
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
