/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiListClipper */

#ifndef _Included_imgui_ImGuiListClipper
#define _Included_imgui_ImGuiListClipper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiListClipper
 * Method:    forEach
 * Signature: (IILimgui/callback/ImListClipperCallback;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiListClipper_forEach
  (JNIEnv *, jclass, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
