/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_extension_imnodes_ImNodesStyle */

#ifndef _Included_imgui_extension_imnodes_ImNodesStyle
#define _Included_imgui_extension_imnodes_ImNodesStyle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    getGridSpacing
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_getGridSpacing
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    setGridSpacing
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_setGridSpacing
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    getNodeCornerRounding
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_getNodeCornerRounding
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    setNodeCornerRounding
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_setNodeCornerRounding
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    getNodePadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_getNodePadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    setNodePadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_setNodePadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    getNodeBorderThickness
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_getNodeBorderThickness
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    setNodeBorderThickness
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_setNodeBorderThickness
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    getLinkThickness
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_getLinkThickness
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    setLinkThickness
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_setLinkThickness
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    getLinkLineSegmentsPerLength
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_getLinkLineSegmentsPerLength
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    setLinkLineSegmentsPerLength
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_setLinkLineSegmentsPerLength
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    getLinkHoverDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_getLinkHoverDistance
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    setLinkHoverDistance
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_setLinkHoverDistance
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    getPinCircleRadius
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_getPinCircleRadius
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    setPinCircleRadius
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_setPinCircleRadius
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    getPinQuadSideLength
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_getPinQuadSideLength
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    setPinQuadSideLength
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_setPinQuadSideLength
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    getPinTriangleSideLength
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_getPinTriangleSideLength
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    setPinTriangleSideLength
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_setPinTriangleSideLength
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    getPinLineThickness
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_getPinLineThickness
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    setPinLineThickness
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_setPinLineThickness
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    getPinHoverRadius
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_getPinHoverRadius
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    setPinHoverRadius
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_setPinHoverRadius
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    getPinOffset
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_extension_imnodes_ImNodesStyle_getPinOffset
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    setPinOffset
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_setPinOffset
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    getMiniMapPadding
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_getMiniMapPadding
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    setMiniMapPadding
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_setMiniMapPadding
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    getMiniMapOffset
 * Signature: (Limgui/ImVec2;)Limgui/ImVec2;
 */
JNIEXPORT jobject JNICALL Java_imgui_extension_imnodes_ImNodesStyle_getMiniMapOffset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    setMiniMapOffset
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_setMiniMapOffset
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    getFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_extension_imnodes_ImNodesStyle_getFlags
  (JNIEnv *, jobject);

/*
 * Class:     imgui_extension_imnodes_ImNodesStyle
 * Method:    setFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_extension_imnodes_ImNodesStyle_setFlags
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
