/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImDrawData */

#ifndef _Included_imgui_ImDrawData
#define _Included_imgui_ImDrawData
#ifdef __cplusplus
extern "C" {
#endif
#undef imgui_ImDrawData_SIZEOF_IM_DRAW_IDX
#define imgui_ImDrawData_SIZEOF_IM_DRAW_IDX 2L
#undef imgui_ImDrawData_SIZEOF_IM_DRAW_VERT
#define imgui_ImDrawData_SIZEOF_IM_DRAW_VERT 20L
#undef imgui_ImDrawData_RESIZE_FACTOR
#define imgui_ImDrawData_RESIZE_FACTOR 5000L
/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListCmdBufferSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_getCmdListCmdBufferSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListCmdBufferElemCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_getCmdListCmdBufferElemCount
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListCmdBufferClipRect
 * Signature: (IILimgui/ImVec4;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_getCmdListCmdBufferClipRect
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListCmdBufferTextureId
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_getCmdListCmdBufferTextureId
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListCmdBufferVtxOffset
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_getCmdListCmdBufferVtxOffset
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListCmdBufferIdxOffset
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_getCmdListCmdBufferIdxOffset
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListIdxBufferSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_getCmdListIdxBufferSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetCmdListIdxBufferData
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_nGetCmdListIdxBufferData
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListVtxBufferSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_getCmdListVtxBufferSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetCmdListVtxBufferData
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_nGetCmdListVtxBufferData
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     imgui_ImDrawData
 * Method:    sizeOfImDrawVert
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_sizeOfImDrawVert
  (JNIEnv *, jclass);

/*
 * Class:     imgui_ImDrawData
 * Method:    sizeOfImDrawIdx
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_sizeOfImDrawIdx
  (JNIEnv *, jclass);

/*
 * Class:     imgui_ImDrawData
 * Method:    getValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImDrawData_getValid
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    getCmdListsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_getCmdListsCount
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    getTotalIdxCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_getTotalIdxCount
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    getTotalVtxCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imgui_ImDrawData_getTotalVtxCount
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    getDisplayPos
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_getDisplayPos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    getDisplayPosX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawData_getDisplayPosX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    getDisplayPosY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawData_getDisplayPosY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    getDisplaySize
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_getDisplaySize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    getDisplaySizeX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawData_getDisplaySizeX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    getDisplaySizeY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawData_getDisplaySizeY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    getFramebufferScale
 * Signature: (Limgui/ImVec2;)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_getFramebufferScale
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    getFramebufferScaleX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawData_getFramebufferScaleX
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    getFramebufferScaleY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImDrawData_getFramebufferScaleY
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    nGetOwnerViewport
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImDrawData_nGetOwnerViewport
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    deIndexAllBuffers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_deIndexAllBuffers
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImDrawData
 * Method:    scaleClipRects
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImDrawData_scaleClipRects
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
