/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGuiStorage */

#ifndef _Included_imgui_ImGuiStorage
#define _Included_imgui_ImGuiStorage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGuiStorage
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGuiStorage_nCreate
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStorage_clear
  (JNIEnv *, jobject);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    getInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiStorage_getInt__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    getInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imgui_ImGuiStorage_getInt__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    setInt
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStorage_setInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    getBool
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiStorage_getBool__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    getBool
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_imgui_ImGuiStorage_getBool__IZ
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    setBool
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStorage_setBool
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    getFloat
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStorage_getFloat__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    getFloat
 * Signature: (IF)F
 */
JNIEXPORT jfloat JNICALL Java_imgui_ImGuiStorage_getFloat__IF
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    setFloat
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStorage_setFloat
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    setAllInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStorage_setAllInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     imgui_ImGuiStorage
 * Method:    buildSortByKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_ImGuiStorage_buildSortByKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
