# Product identity is independent from optimization/debug information.
set(AMCL_BUILD_PRODUCT "" CACHE STRING "AMCL product identity (required)")
if(NOT AMCL_BUILD_PRODUCT MATCHES "^(default|sideload|store|desktop)$")
    message(FATAL_ERROR "AMCL_BUILD_PRODUCT must name a registered product")
endif()
set(AMCL_DEVELOPER_DIAGNOSTICS OFF)
if(AMCL_BUILD_PRODUCT STREQUAL "default")
    set(AMCL_DEVELOPER_DIAGNOSTICS ON)
endif()
if(MC_OHOS_BUILD_TESTS STREQUAL "AUTO")
    set(_tests OFF)
    if(AMCL_DEVELOPER_DIAGNOSTICS AND CMAKE_BUILD_TYPE STREQUAL "Debug")
        set(_tests ON)
    endif()
    set(MC_OHOS_BUILD_TESTS ${_tests} CACHE BOOL "Build feasibility test modules" FORCE)
endif()
option(AMCL_INPUT_TRACE "Emit verbose per-event input diagnostics" OFF)
# Vulkan 逐资源 trace 单独显式申请；保持默认关闭，不随 Debug 或开发产品自动开启。
# 新诊断项只追加，保证旧发布记录中的 mask 位含义稳定，当前新项使用位 9（512）。
option(AMCL_VULKAN_WSI_TRACE "Emit Vulkan WSI resource and procedure diagnostics" OFF)
set(_diagnostic_flags MC_OHOS_BUILD_TESTS AMCL_INPUT_TRACE
    AMCL_MG_FRAME_STATS AMCL_MG_FRAME_STATS_GL_SCOPES AMCL_MG_FRAME_STATS_EXHAUSTIVE
    AMCL_MG_UPLOAD_PROBE AMCL_STACK_SAMPLER AMCL_INPUT_GATE0_TELEMETRY AMCL_VULKAN_WSI_TRACE)
set(AMCL_DIAGNOSTICS_MASK 0)
if(AMCL_DEVELOPER_DIAGNOSTICS)
    set(AMCL_DIAGNOSTICS_MASK 1)
endif()
set(_bit 2)
foreach(_flag IN LISTS _diagnostic_flags)
    if(${_flag})
        if(NOT AMCL_DEVELOPER_DIAGNOSTICS)
            message(FATAL_ERROR "${_flag} is default-only; rejected for ${AMCL_BUILD_PRODUCT}/${CMAKE_BUILD_TYPE}")
        endif()
        math(EXPR AMCL_DIAGNOSTICS_MASK "${AMCL_DIAGNOSTICS_MASK} | ${_bit}")
    endif()
    math(EXPR _bit "${_bit} * 2")
endforeach()
set(AMCL_DIAGNOSTICS_MARKER "AMCL_DIAGNOSTICS_V1:product=${AMCL_BUILD_PRODUCT};mask=${AMCL_DIAGNOSTICS_MASK};")
configure_file("${CMAKE_CURRENT_LIST_DIR}/product_diagnostics_config.h.in"
    "${CMAKE_CURRENT_BINARY_DIR}/product_diagnostics_config.h" @ONLY)
message(STATUS "${AMCL_DIAGNOSTICS_MARKER}")

set(AMCL_PRODUCT_HILOG_HEADER "${CMAKE_CURRENT_LIST_DIR}/../utils/product_hilog.h")
function(amcl_apply_diagnostic_policy target)
    target_sources(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/utils/product_diagnostics_identity.cpp")
    target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_BINARY_DIR}")
    target_compile_options(${target} PRIVATE
        "-include" "${AMCL_PRODUCT_HILOG_HEADER}")
    if(NOT AMCL_INPUT_TRACE)
        target_compile_definitions(${target} PRIVATE AMCL_INPUT_TRACE_SAMPLE_INTERVAL=0)
    endif()
endfunction()
