// Generated by scripts/generate-graphics-profile-mirror.mjs. Do not edit.
// Source: launch/src/main/ets/GraphicsProfileRegistry.ets
#ifndef AMCL_GRAPHICS_PROFILE_MIRROR_GENERATED_H
#define AMCL_GRAPHICS_PROFILE_MIRROR_GENERATED_H
#include <cstddef>
namespace amcl { namespace graphics {
struct GraphicsProfileMetadata {
    const char* id;
    const char* api;
    const char* nativeRoute;
    const char* transport;
    const char* requirementId;
    const char* const* requirementIds;
    std::size_t requirementCount;
    const char* admission;
    const char* glLibName;
    const char* capabilityKind;
    unsigned providerMask;
    unsigned platformMask;
    bool systemLibrary;
    // 与 ArkTS 同源的宿主能力；运行中的驱动准入仍独立执行。
    const char* contextApi;
    const char* glfwSharedContext;
    const char* glfwAuxiliaryWindow;
    const char* sdlAuxiliaryWindow;
    const char* parkingContext;
};
inline constexpr const char* kDefaultGraphicsProfileId = "mobileglues";
inline constexpr const char* const kGraphicsRequirements0[] = {"legacy-gl"};
inline constexpr const char* const kGraphicsRequirements1[] = {"legacy-gl4es"};
inline constexpr const char* const kGraphicsRequirements2[] = {"mobilegl-direct-vulkan-v1", "mobilegl-sdl3-validation-v1"};
inline constexpr const char* const kGraphicsRequirements3[] = {"desktop-system-gl-validation-v1"};
inline constexpr const char* const kGraphicsRequirements4[] = {"minecraft-26.2-conservative-v1", "minecraft-26.3-pre1-vulkan-conservative-v1", "minecraft-26.3-sdl-vulkan-conservative-v1", "minecraft-26.4-snapshot1-sdl-vulkan-v1"};
inline constexpr GraphicsProfileMetadata kGraphicsProfiles[] = {
    {"mobileglues", "OPENGL", "mobileglues", "UNKNOWN", "legacy-gl", kGraphicsRequirements0, sizeof(kGraphicsRequirements0) / sizeof(kGraphicsRequirements0[0]), "LEGACY", "libamcl_gl_host.so", "legacy", 3u, 3u, false, "gles", "probe-required", "probe-required", "supported", "supported"},
    {"gl4es", "OPENGL", "gl4es", "UNKNOWN", "legacy-gl4es", kGraphicsRequirements1, sizeof(kGraphicsRequirements1) / sizeof(kGraphicsRequirements1[0]), "LEGACY", "libgl4es.so", "legacy", 3u, 3u, false, "gles", "probe-required", "probe-required", "supported", "supported"},
    {"mobilegl", "OPENGL", "mobilegl", "YES", "mobilegl-direct-vulkan-v1", kGraphicsRequirements2, sizeof(kGraphicsRequirements2) / sizeof(kGraphicsRequirements2[0]), "VALIDATION", "libmobilegl.so", "vulkan", 3u, 3u, false, "desktop-gl", "probe-required", "probe-required", "supported", "supported"},
    {"nativegl", "OPENGL", "nativegl", "UNKNOWN", "desktop-system-gl-validation-v1", kGraphicsRequirements3, sizeof(kGraphicsRequirements3) / sizeof(kGraphicsRequirements3[0]), "VALIDATION", "libGLv4.so", "native-gl", 3u, 3u, true, "desktop-gl", "probe-required", "probe-required", "supported", "supported"},
    {"minecraft-vulkan", "VULKAN", "minecraft-vulkan", "YES", "minecraft-26.2-conservative-v1", kGraphicsRequirements4, sizeof(kGraphicsRequirements4) / sizeof(kGraphicsRequirements4[0]), "VALIDATION", "", "vulkan", 3u, 3u, false, "none", "unsupported", "unsupported", "unsupported", "unsupported"},
};
inline constexpr std::size_t kGraphicsProfileCount = sizeof(kGraphicsProfiles) / sizeof(kGraphicsProfiles[0]);
constexpr bool GraphicsProfileStringEqual(const char* a, const char* b) {
    if (a == nullptr || b == nullptr) return a == b;
    while (*a != '\0' && *a == *b) { ++a; ++b; }
    return *a == *b;
}
constexpr const GraphicsProfileMetadata* FindGraphicsProfile(const char* id) {
    for (std::size_t i = 0; i < kGraphicsProfileCount; ++i) {
        if (GraphicsProfileStringEqual(id, kGraphicsProfiles[i].id)) return &kGraphicsProfiles[i];
    }
    return nullptr;
}
constexpr bool GraphicsProfileSupportsRequirement(const GraphicsProfileMetadata& profile, const char* requirement) {
    if (requirement == nullptr) return false;
    for (std::size_t i = 0; i < profile.requirementCount; ++i) {
        if (GraphicsProfileStringEqual(requirement, profile.requirementIds[i])) return true;
    }
    return false;
}
constexpr bool GraphicsProfileSupportsProvider(const GraphicsProfileMetadata& profile, const char* provider) {
    const unsigned mask = GraphicsProfileStringEqual(provider, "GLFW") ? 1u
        : (GraphicsProfileStringEqual(provider, "SDL3") ? 2u : 0u);
    return mask != 0u && (profile.providerMask & mask) != 0u;
}
constexpr bool GraphicsProfileSupportsPlatform(const GraphicsProfileMetadata& profile, const char* platform) {
    const unsigned mask = GraphicsProfileStringEqual(platform, "MOBILE") ? 1u
        : (GraphicsProfileStringEqual(platform, "DESKTOP") ? 2u : 0u);
    return mask != 0u && (profile.platformMask & mask) != 0u;
}
struct GeneratedGlLibrary {
    const char* id;
    const char* glLibName;
    bool availableInThisBuild;
    const char* unavailableReason;
    bool systemLibrary;
};
// Legacy API describes compiled routing support; artifact admission is checked separately.
inline constexpr GeneratedGlLibrary kLegacyGlLibraries[] = {
    {"mobileglues", "libamcl_gl_host.so", true, nullptr, false},
    {"gl4es", "libgl4es.so", true, nullptr, false},
    {"mobilegl", "libmobilegl.so", true, nullptr, false},
    {"nativegl", "libGLv4.so", true, nullptr, true},
};
constexpr bool GraphicsProfileMirrorValid() {
    for (std::size_t i = 0; i < kGraphicsProfileCount; ++i) {
        const auto& p = kGraphicsProfiles[i];
        if (p.id[0] == '\0' || p.providerMask == 0u || p.platformMask == 0u) return false;
        const bool isGl = GraphicsProfileStringEqual(p.api, "OPENGL");
        if (isGl == (p.glLibName[0] == '\0')) return false;
        for (std::size_t j = i + 1; j < kGraphicsProfileCount; ++j) {
            if (GraphicsProfileStringEqual(p.id, kGraphicsProfiles[j].id)) return false;
        }
    }
    return true;
}
static_assert(GraphicsProfileMirrorValid(), "invalid generated graphics profile mirror");
} }
#endif
